kind: Pod
apiVersion: v1
metadata:
  name: cleanup-pod
  labels:
    app: cleanup-pod
spec:
  containers:
    - image: registry.access.redhat.com/ubi8/ubi-micro 
      command: ["sleep"]
      args: ["infinity"]
      name: ubuntu
      volumeMounts:
        - name: mongodump
          mountPath: "/dump"
      lifecycle:
            postStart:
              exec:
                command: ["bash", "-c", "rm -rf /dump/.velero"]
  volumes:
    - name: mongodump
      persistentVolumeClaim:
        claimName: my-mongodump
