{
 "title": "IBM Cloud Pak for AIOps Component - Log Integrations",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Log Integrations Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Log Integrations Overview\n\nIBM Cloud Pak for AIOps is capable of ingesting logs from a variety of sources.\nThis dashboard will provide insight into the health & performance of the following integrations:\nCustom, ELK, Falcon LogScale, Mezmo, Splunk\n\nOnly integrations that have been created in the IBM Cloud Pak for AIOps Integrations page will have metrics visible here."
     }
    },
    {
     "type": "stat",
     "description": "Count that tracks the number of pods that were newly created within the time range.\n",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 360 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Log Integration Component Pods",
     "type": "table",
     "description": "This panel displays the number of active pods for all defined Log integration pods. Pods stuck in \"Pending\" or \"Unknown\" states for prolonged periods of time are problematic and may result in loss of functionality.",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 361 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Log Integration Component Pods Uptime",
     "type": "timeseries",
     "description": "Pod uptimes for log integrations",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 361 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utlization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Custom Logs Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ibm-custom-logs-conn-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-custom-logs-conn-.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-custom-logs-conn-.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Custom Logs Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"ibm-custom-logs-conn-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-custom-logs-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-custom-logs-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "ELK Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ibm-elk-logs-conn-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-elk-logs-conn-.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-elk-logs-conn-.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "ELK Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"ibm-elk-logs-conn-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-elk-logs-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-elk-logs-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Falcon LogScale Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ibm-falcon-logs-conn-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-falcon-logs-conn-.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-falcon-logs-conn-.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Falcon LogScale Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"ibm-falcon-logs-conn-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-falcon-logs-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-falcon-logs-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Mezmo Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ibm-mezmo-logs-conn-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-mezmo-logs-conn-.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-mezmo-logs-conn-.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Mezmo Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"ibm-mezmo-logs-conn-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-mezmo-logs-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-mezmo-logs-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Splunk Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"splunk-conn-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"splunk-conn-.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"splunk-conn-.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Splunk Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"splunk-conn-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"splunk-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"splunk-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    }
   ]
  },
  { "title": "Total Logs collected", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Logs collected ",
   "type": "stat",
   "description": "Total number of logs collected within the time range across all logs integrations.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[$__range]) or vector(0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Logs collected per integration ",
   "type": "piechart",
   "description": "Total number of logs collected by each integration within the time range.",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[$__range])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[$__range])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[$__range])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[$__range])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[$__range])\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Log collection rate ",
   "type": "timeseries",
   "description": "Per-second rates of logs collected by each integration..",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "logs/s" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[3m])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[3m])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[3m])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[3m])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[3m])\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Custom Log Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_custom_historical_logs_run_count_total[$__range]) or vector(0)) + \nsum(increase(ibm_aiops_logconnector_custom_live_logs_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_custom_historical_logs_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_custom_live_logs_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_custom_historical_logs_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_custom_live_logs_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs collected per integration ",
     "type": "piechart",
     "description": "Total number of logs collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Log collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of logs collected by each integration..",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Logs collected ",
     "type": "stat",
     "description": "Total number of logs collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ELK Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_elk_historical_logs_run_count_total[$__range]) or vector(0)) + \nsum(increase(ibm_aiops_logconnector_elk_live_logs_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_elk_historical_logs_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_elk_live_logs_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_elk_historical_logs_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_elk_live_logs_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs collected per integration ",
     "type": "piechart",
     "description": "Total number of logs collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Log collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of logs collected by each integration..",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Logs collected ",
     "type": "stat",
     "description": "Total number of logs collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Falcon LogScale Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_logscale_historical_logs_run_count_total[$__range]) or vector(0)) + sum(increase(ibm_aiops_logconnector_logscale_live_logs_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 58 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_logscale_historical_logs_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_logscale_live_logs_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 58 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_logscale_historical_logs_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_logscale_live_logs_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs collected per integration ",
     "type": "piechart",
     "description": "Total number of logs collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Log collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of logs collected by each integration..",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Logs collected ",
     "type": "stat",
     "description": "Total number of logs collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mezmo Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_mezmo_historical_logs_run_count_total[$__range]) or vector(0)) + sum(increase(ibm_aiops_logconnector_mezmo_live_logs_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 68 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_mezmo_historical_logs_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_mezmo_live_logs_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 68 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_mezmo_historical_logs_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_mezmo_live_logs_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs collected per integration ",
     "type": "piechart",
     "description": "Total number of logs collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Log collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of logs collected by each integration..",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Logs collected ",
     "type": "stat",
     "description": "Total number of logs collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Splunk Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_splunk_historical_logs_run_count_total[$__range]) or vector(0)) + sum(increase(ibm_aiops_logconnector_splunk_live_logs_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_splunk_historical_logs_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_splunk_live_logs_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_splunk_historical_logs_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_splunk_live_logs_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs collected per integration ",
     "type": "piechart",
     "description": "Total number of logs collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Log collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of logs collected by each integration..",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Logs collected ",
     "type": "stat",
     "description": "Total number of logs collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}