{
 "title": "IBM Cloud Pak for AIOps Component - Web UI",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Web UI Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Web UI Component Overview\n\nThe IBM Cloud Pak for AIOps web UI is built out of the following sub-components:\n- aiops-base-ui: AIOps Home page UI\n- aiops-akora-ui: AIOps Core UI (Incident/Alert Management, Topology/Policies UI & RBA) \n- aiops-connections-ui: AIOps Integrations UI\n- aiops-model-ui: AIOps Model Management Page\n- aiops-insights-ui: AIOps Insights "
     }
    },
    {
     "type": "stat",
     "description": "Count that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 435 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Web UI component pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 436 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Web UI Pods Uptime",
     "type": "timeseries",
     "description": "Pod Uptimes for web UI component pods",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 436 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - kube_pod_start_time{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 445 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 445 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", container!=\"\", container!=\"POD\", container!=\"\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 446 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 446 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\", container!=\"\", container!=\"POD\", container!=\"\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Home Page UI CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-base-ui.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-base-ui.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-base-ui.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Home Page UI Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-base-ui.*\", container!=\"\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-base-ui.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-base-ui.*\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Core UI CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 455 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-akora-ui.*\"})",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-akora-ui.*\", resource=\"cpu\"}) by (pod)",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-akora-ui.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Core UI Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 455 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-akora-ui.*\", container!=\"\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-akora-ui.*\", resource=\"memory\"})",
       "legendFormat": "requests - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-akora-ui.*\", resource=\"memory\"})",
       "legendFormat": "limits - {{pod}}"
      }
     ]
    },
    {
     "title": "Integrations UI CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 463 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-connections-ui-.*\" }) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-connections-ui-.*\" , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-connections-ui-.*\" , resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Integrations UI Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 463 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-connections-ui-.*\" , container!=\"\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-connections-ui-.*\" , resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-connections-ui-.*\" , resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "AI Model Management UI CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 471 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-ai-model-ui.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ai-model-ui.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ai-model-ui.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "AI Model Management UI Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 471 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-ai-model-ui.*\", container!=\"\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ai-model-ui.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ai-model-ui.*\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Insights UI CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 479 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-insights-ui-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-insights-ui-.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-insights-ui-.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Insights UI Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 479 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-insights-ui-.*\", container!=\"\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-insights-ui-.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-insights-ui-.*\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Home page UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request totals",
     "type": "bargauge",
     "description": "2xx, 4xx, & 5xx request counts within the time range.\n\nThese counts may increase by more than 1 at a time. What appears to be one request in the UI, may be several in the backed and these counts will reflect that.",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"2..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"4..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"5..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "400 errors",
     "type": "stat",
     "description": "Count that tracks the number of 400 **bad request** errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"400\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "401 errors",
     "type": "stat",
     "description": "Count that tracks the number of 401 **unauthorized** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"401\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "403 errors",
     "type": "stat",
     "description": "Count that tracks the number of 403 forbidden errors in the within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"403\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "404 errors",
     "type": "stat",
     "description": "Count that tracks the number of 404 **not found** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"404\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "407 errors",
     "type": "stat",
     "description": "Count that tracks the number of 407 \"proxy auth required\" errors UI within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"407\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "500 errors",
     "type": "stat",
     "description": "Count that tracks the number of 500 \"internal server\" errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"500\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "501 errors",
     "type": "stat",
     "description": "Count that tracks the number of 501 \"not implemented\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"501\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "502 errors",
     "type": "stat",
     "description": "Count that tracks the number of 502 \"bad gateway\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"502\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "503 errors",
     "type": "stat",
     "description": "Count that tracks the number of 503 \"service unavailable\"within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"503\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "504 errors",
     "type": "stat",
     "description": "Count that tracks the number of 504 \"gateway timeout\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"504\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request rates",
     "type": "timeseries",
     "description": "Average request rates per minute by request & response",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_aiops_base_ui_request_total{code=~\"2..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_base_ui_request_total{code=~\"4..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_base_ui_request_total{code=~\"5..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Core UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request totals",
     "type": "bargauge",
     "description": "2xx, 4xx, & 5xx request counts within the time range.\n\nThese counts may increase by more than 1 at a time. What appears to be one request in the UI, will be several in the backend and these counts will reflect that.",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"2..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"4..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"5..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "400 errors",
     "type": "stat",
     "description": "Count that tracks the number of 400 **bad request** errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"400\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "401 errors",
     "type": "stat",
     "description": "Count that tracks the number of 401 **unauthorized** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"401\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "403 errors",
     "type": "stat",
     "description": "Count that tracks the number of 403 forbidden errors in the within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"403\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "404 errors",
     "type": "stat",
     "description": "Count that tracks the number of 404 **not found** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"404\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "407 errors",
     "type": "stat",
     "description": "Count that tracks the number of 407 \"proxy auth required\" errors UI within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"407\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "500 errors",
     "type": "stat",
     "description": "Count that tracks the number of 500 \"internal server\" errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"500\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "501 errors",
     "type": "stat",
     "description": "Count that tracks the number of 501 \"not implemented\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"501\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "502 errors",
     "type": "stat",
     "description": "Count that tracks the number of 502 \"bad gateway\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"502\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "503 errors",
     "type": "stat",
     "description": "Count that tracks the number of 503 \"service unavailable\"within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"503\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "504 errors",
     "type": "stat",
     "description": "Count that tracks the number of 504 \"gateway timeout\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"504\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rates",
     "type": "timeseries",
     "description": "Average request rates per minute by request & response",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_aiops_akora_ui_request_total{code=~\"2..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_akora_ui_request_total{code=~\"4..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_akora_ui_request_total{code=~\"5..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Integrations page UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request totals",
     "type": "bargauge",
     "description": "2xx, 4xx, & 5xx request counts within the time range.\n\nThese counts may increase by more than 1 at a time. What appears to be one request in the UI, may be several in the backed and these counts will reflect that.",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"2..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"4..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"5..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "400 errors",
     "type": "stat",
     "description": "Count that tracks the number of 400 **bad request** errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"400\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "401 errors",
     "type": "stat",
     "description": "Count that tracks the number of 401 **unauthorized** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"401\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "403 errors",
     "type": "stat",
     "description": "Count that tracks the number of 403 forbidden errors in the within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"403\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "404 errors",
     "type": "stat",
     "description": "Count that tracks the number of 404 **not found** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"404\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "407 errors",
     "type": "stat",
     "description": "Count that tracks the number of 407 \"proxy auth required\" errors UI within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"407\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "500 errors",
     "type": "stat",
     "description": "Count that tracks the number of 500 \"internal server\" errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"500\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "501 errors",
     "type": "stat",
     "description": "Count that tracks the number of 501 \"not implemented\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"501\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "502 errors",
     "type": "stat",
     "description": "Count that tracks the number of 502 \"bad gateway\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"502\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "503 errors",
     "type": "stat",
     "description": "Count that tracks the number of 503 \"service unavailable\"within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"503\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "504 errors",
     "type": "stat",
     "description": "Count that tracks the number of 504 \"gateway timeout\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"504\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rates",
     "type": "timeseries",
     "description": "Average request rates per minute by request & response",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_aiops_integration_ui_request_total{code=~\"2..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_integration_ui_request_total{code=~\"4..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_integration_ui_request_total{code=~\"5..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Model Management UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request totals",
     "type": "bargauge",
     "description": "2xx, 4xx, & 5xx request counts within the time range.\n\nThese counts may increase by more than 1 at a time. What appears to be one request in the UI, may be several in the backed and these counts will reflect that.",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"2..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"4..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"5..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "400 errors",
     "type": "stat",
     "description": "Count that tracks the number of 400 **bad request** errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 42 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"400\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "401 errors",
     "type": "stat",
     "description": "Count that tracks the number of 401 **unauthorized** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"401\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "403 errors",
     "type": "stat",
     "description": "Count that tracks the number of 403 forbidden errors in the within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 42 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"403\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "404 errors",
     "type": "stat",
     "description": "Count that tracks the number of 404 **not found** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 42 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"404\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "407 errors",
     "type": "stat",
     "description": "Count that tracks the number of 407 \"proxy auth required\" errors UI within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 42 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"407\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "500 errors",
     "type": "stat",
     "description": "Count that tracks the number of 500 \"internal server\" errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 45 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"500\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "501 errors",
     "type": "stat",
     "description": "Count that tracks the number of 501 \"not implemented\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"501\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "502 errors",
     "type": "stat",
     "description": "Count that tracks the number of 502 \"bad gateway\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 45 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"502\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "503 errors",
     "type": "stat",
     "description": "Count that tracks the number of 503 \"service unavailable\"within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 45 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"503\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "504 errors",
     "type": "stat",
     "description": "Count that tracks the number of 504 \"gateway timeout\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 45 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"504\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rates",
     "type": "timeseries",
     "description": "Average request rates per minute by request & response",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"2..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"4..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"5..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Insights UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request totals",
     "type": "bargauge",
     "description": "2xx, 4xx, & 5xx request counts within the time range.\n\nThese counts may increase by more than 1 at a time. What appears to be one request in the UI, may be several in the backed and these counts will reflect that.",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"2..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"4..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"5..\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "400 errors",
     "type": "stat",
     "description": "Count that tracks the number of 400 **bad request** errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"400\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "401 errors",
     "type": "stat",
     "description": "Count that tracks the number of 401 **unauthorized** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"401\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "403 errors",
     "type": "stat",
     "description": "Count that tracks the number of 403 forbidden errors in the within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"403\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "404 errors",
     "type": "stat",
     "description": "Count that tracks the number of 404 **not found** errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"404\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "407 errors",
     "type": "stat",
     "description": "Count that tracks the number of 407 \"proxy auth required\" errors UI within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"407\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "500 errors",
     "type": "stat",
     "description": "Count that tracks the number of 500 \"internal server\" errors within the time range.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 58 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"500\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "501 errors",
     "type": "stat",
     "description": "Count that tracks the number of 501 \"not implemented\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"501\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "502 errors",
     "type": "stat",
     "description": "Count that tracks the number of 502 \"bad gateway\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 58 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"502\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "503 errors",
     "type": "stat",
     "description": "Count that tracks the number of 503 \"service unavailable\"within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 58 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"503\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "504 errors",
     "type": "stat",
     "description": "Count that tracks the number of 504 \"gateway timeout\" errors within the time range",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 58 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"504\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rates",
     "type": "timeseries",
     "description": "Average request rates per minute by request & response",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_aiops_insights_ui_request_total{code=~\"2..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_insights_ui_request_total{code=~\"4..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_aiops_insights_ui_request_total{code=~\"5..\"}[3m]) * 60) by (code, method)",
       "legendFormat": "{{method}} - {{code}}"
      }
     ]
    }
   ]
  }
 ]
}