{
 "title": "IBM Cloud Pak for AIOps - Top Level",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Node Health", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 1 } },
  { "title": "CPU Usage", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 6, "y": 1 } },
  { "title": "Memory Usage", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 1 } },
  { "title": "PVC  Usage (Namespace only)", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Healthy Nodes",
   "type": "stat",
   "description": "Current number of nodes in a non-ready state across the entire cluster. Prolonged node outages can disrupt functionality if not handled quickly. Review the health of your nodes to get them back in a ready state. ",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", node=~\".*\", status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "stat",
   "description": "Current number of nodes in a non-ready state across the entire cluster. Prolonged node outages can disrupt functionality if not handled quickly. Review the health of your nodes to get them back in a ready state. ",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", node=~\".*\", status=~\"False|Unknown\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "This panel shows the CPU utilization across the entire cluster. Consistently high CPU usage will lead to slower processing, ensure CPU is allocated appropriately.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^.*$\"}[5m])) / sum (machine_cpu_cores{node=~\"^.*$\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "This panel shows the memory utilization across the entire cluster. Consistently high memory usage can lead to pods getting killed, potentially resulting in loss of functionality. Ensure allocated memory is sufficient to avoid this.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"})\n/\nsum(machine_memory_bytes)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceeding 50%",
   "type": "stat",
   "description": "Number of PVCs that have exceeded 50% of their allocated storage within the selected namespace . PVCs approaching/exceeding 100% will cause pod failures, leading to loss of functionality. To view more PVC details, refer to the Health dashboard under the \"Storage Health\" section.",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "count(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}/kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"} * 100 > 50) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceeding 80%",
   "type": "stat",
   "description": "Number of PVCs that have exceeded 80% of their allocated storage within the selected namespace . PVCs approaching/exceeding 100% will cause pod failures, leading to loss of functionality. To view more PVC details, refer to the Health dashboard under the \"Storage Health\" section.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "targets": [
    {
     "expr": "count(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}/kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"} * 100 > 80) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Component Pod Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Cassandra",
   "type": "stat",
   "description": "Refer to the \"Event Processing dashboard\" -> \"Policy Automation Dependencies\" for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"aiops-topology-cassandra-.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CouchDB",
   "type": "stat",
   "description": "Count that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*couchdb.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink",
   "type": "stat",
   "description": "Count that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"aiops-ir-lifecycle-flink-.*\", pod!~\".*validation.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "stat",
   "description": "Refer to the \"Event Processing dashboard\" -> \"Policy Automation Dependencies\" for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"iaf-system-kafka.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MinIO",
   "type": "stat",
   "description": "Count that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*minio.*\", pod!~\".*validation.*|.*create.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opensearch",
   "type": "stat",
   "description": "Refer to the \"Event Processing dashboard\" -> \"Datalayer Dependencies\" for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"aiops-opensearch.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "description": "Refer to the \"Event Processing dashboard\" -> \"Policy Automation Dependencies\" for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*core-postgres.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analytics Component",
   "type": "stat",
   "description": "Refer to the \"Analytics\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"aiops-ir-analytics-.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datalayer Component",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"aiops-ir-core-ncodl-.*\", pod!~\".*cjob.*\", pod!~\".*presetup.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Integrations Component",
   "type": "stat",
   "description": "Refer to the \"Event Integrations\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*|.*-webhook-connector-.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Integrations Component",
   "type": "stat",
   "description": "Refer to the \"Log Integrations\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"ibm-falcon-logs-conn-.*|ibm-custom-logs-conn-.*|ibm-elk-logs-conn-.*|splunk-conn-.*|ibm-mezmo-logs-conn-.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric Integrations Component",
   "type": "stat",
   "description": "Refer to the \"Metric Integrations\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"nrelic-conn-.*|ibm-grpc-instana-connector-.*|appd-conn-.*|ibm-awscw-conn-.*|splunk-conn-.*|ibm-zabbix-conn-.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Automation Component",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*-lifecycle-.*\", pod!~\".*validation.*\", pod!~\".*job.*\", pod!~\".*operand-deployment-lifecycle-manager.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RBA Component Stability",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"aiops-ir-core-rba.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topology Component",
   "type": "stat",
   "description": "Refer to the \"Topology\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web UI Component Stability",
   "type": "stat",
   "description": "Refer to the \"Web UI\" dashboard for further details.\n\nCount that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime time graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\"aiops-base-ui.*|aiops-akora-ui.*|aiops-ai-model-ui.*|aiops-connections-ui-.*|aiops-insights-ui-.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Component Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Webhook Errors",
   "type": "stat",
   "description": "Refer to the \"Event Integrations\" dashboard -> \"Webhook integration\" for further details.\n\nCount of  exceptions, and status failures that occurred within the Webhook integration.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(connectors_sdk_connectorexceptions_thrown_total{pod=~\".*-webhook-.*\"}[$__range]) or vector(0)) + \n  sum(increase(connector_sdk_status_failed_total{pod=~\".*-webhook-.*\"}[$__range]) or vector(0))\n)\n",
     "legendFormat": "Webhook"
    }
   ]
  },
  {
   "title": "Event Classification Errors",
   "type": "stat",
   "description": "Refer to the \"Analytics\" dashboard for further details.\n\nCount of event classification errors.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(ibm_aiops_mime_classfier_cassandra_errors_total[$__range])) + \nsum(increase(ibm_aiops_mime_classfier_http_requests_errors_total[$__range])) + \nsum(increase(ibm_aiops_mime_classfier_kafka_errors_total[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Request Errors",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard -> \"Datalayer Component\" for further details.\n\nTotal failure count for alert expire/close/delete actions executed by the Job Manager service that occurred within the time range.\n\n- **Alert expire**: occurs when an alert's expiration team has been reached\n- **Alert close**: occurs when alert expires or is closed by an event or triggered by manual user action in the UI\n- **Alert delete**: occurs after an alert has been closed for a period of time. This will delete it from the database",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ibm_aiops_ircore_ncodl_jobmgr_job_alert_delete_counter{container=\"jobmgr\", kind=\"failed\"}[$__range]) or vector(0)) + \nsum(increase(ibm_aiops_ircore_ncodl_jobmgr_job_alert_close_counter{container=\"jobmgr\", kind=\"failed\"}[$__range]) or vector(0)) + \nsum(increase(ibm_aiops_ircore_ncodl_jobmgr_job_alert_expire_counter{container=\"jobmgr\", kind=\"failed\"}[$__range]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incident Request Errors",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard -> \"Datalayer Component\" for further details.\n\nTotal failure count for incident close/delete actions executed by the Job Manager service that occurred within the time range.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ibm_aiops_ircore_ncodl_jobmgr_job_story_close_counter{container=\"jobmgr\", kind=\"failed\"}[$__range]) or vector(0)) + sum(increase(ibm_aiops_ircore_ncodl_jobmgr_job_story_delete_counter{container=\"jobmgr\", kind=\"failed\"}[$__range]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instana Errors",
   "type": "stat",
   "description": "Refer to the \"Event Integrations\" dashboard -> \"Instana integration\" for further details.\n\nCount of dropped kafka messages, exceptions, and status failures that occurred within the Instana integration.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(connectors_sdk_connectorexceptions_thrown_total{pod=~\".*-instana-.*\"}[$__range]) or vector(0)) + \n  sum(increase(connector_sdk_status_failed_total{pod=~\".*-instana-.*\"}[$__range]) or vector(0)) +\n  sum(increase(connector_sdk_kafka_consumer_dropped_total{pod=~\".*-instana-.*\"}[$__range]) or vector(0))\n)\n",
     "legendFormat": "Instana"
    }
   ]
  },
  {
   "title": "Netcool Errors",
   "type": "stat",
   "description": "Refer to the \"Event Integrations\" dashboard -> \"Netcool integration\" for further details.\n\nCount of dropped kafka messages, exceptions, and status failures that occurred within the Netcool integration.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(connectors_sdk_connectorexceptions_thrown_total{pod=~\"netcool-conn-.*\"}[$__range]) or vector(0)) + \n  sum(increase(connector_sdk_status_failed_total{pod=~\"netcool-conn-.*\"}[$__range]) or vector(0)) +\n  sum(increase(connector_sdk_kafka_consumer_dropped_total{pod=~\".*-instana-.*\"}[$__range]) or vector(0))\n) or vector(0)\n",
     "legendFormat": "Netcool"
    }
   ]
  },
  {
   "title": "Training Errors",
   "type": "stat",
   "description": "Refer to the \"Analytics\" dashboard for further details.\n\nCount of AI training errors.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(ibm_aiops_training_spark_cluster_drivers_FAILED_count[$__range])) + \n  sum(increase(ibm_aiops_training_spark_lack_of_resource_failure_total[$__range])) + \n  sum(increase(ibm_aiops_training_spark_cluster_drivers_KILLED_count[$__range])) + \n  sum(increase(ibm_aiops_training_spark_submission_failed_total[$__range]))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Action Errors",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard -> \"RBA Component\" for further details.\n\nCount of Actions that failed to start or completed unsuccessfully.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(ibm_aiops_rba_as_action_start_failed[$__range]) or vector(0)) + \n  sum(increase(ibm_aiops_rba_as_actions_finished{status=\"unsuccessful\"}[$__range]) or vector(0))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runbook Errors",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard -> \"RBA Component\" for further details.\n\nCount of runbook executions that failed to start or completed unsuccessfully",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(ibm_aiops_rba_rbs_runbooks_start_failed[$__range]) or vector(0))+\n  sum(increase(ibm_aiops_rba_rbs_runbooks_finished{status=\"unsuccessful\"}[$__range]) or vector(0))\n) or vector(0)\n",
     "legendFormat": "Runbook Failures"
    }
   ]
  },
  {
   "title": "Topology Database Query Errors",
   "type": "stat",
   "description": "Refer to the \"Topology\" dashboard for further details.\n\nCount of database query failures made by the Topology Services within the time range",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-merge\"}[$__range]) or vector(0)) + \n  sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-status\"}[$__range]) or vector(0)) +\n  sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-layout\"}[$__range]) or vector(0)) +\n  sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-topology\"}[$__range]) or vector(0))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "400 Errors",
   "type": "stat",
   "description": "Refer to the \"Web UI\" dashboard for further details.\n\nCount of 400 errors that occurred within the time range.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"4..\"}[$__range]) or vector(0)) + \n  sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"4..\"}[$__range]) or vector(0)) + \n  sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"4..\"}[$__range]) or vector(0)) +\n  sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"4..\"}[$__range]) or vector(0)) +\n  sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"4..\"}[$__range]) or vector(0))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 Errors",
   "type": "stat",
   "description": "Refer to the \"Web UI\" dashboard for further details.\n\nCount of 500 errors that occurred within the time range.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "expr": "round(\n  sum(increase(ibm_aiops_aiops_akora_ui_request_total{code=~\"5..\"}[$__range]) or vector(0)) + \n  sum(increase(ibm_aiops_aiops_base_ui_request_total{code=~\"5..\"}[$__range]) or vector(0)) + \n  sum(increase(ibm_aiops_aiops_integration_ui_request_total{code=~\"5..\"}[$__range]) or vector(0)) +\n  sum(increase(ibm_aiops_aiops_ai_models_ui_request_total{code=~\"5..\"}[$__range]) or vector(0)) +\n  sum(increase(ibm_aiops_aiops_insights_ui_request_total{code=~\"5..\"}[$__range]) or vector(0))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Events ingested",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard -> \"Policy Automation message I/O\" for further details.\n\nEvents ingested within the time range.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.lifecycle.input.events\"}[$__range]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts created/updated",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard -> \"Policy Automation message I/O\" for further details.\n\nAlerts created/updated within the time range.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.alerts\"}[$__range]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incidents created/updated",
   "type": "stat",
   "description": "Refer to the \"Event Processing\" dashboard -> \"Policy Automation message I/O\" for further details.\n\nIncidents created/updated within the time range.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.stories\"}[$__range]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topology Observer Traffic (Bytes)",
   "type": "stat",
   "description": "Refer to the \"Topology\" dashboard\" for further details.\n\nTotal number of bytes sent by Topology Observers to the central Topology Service within the time range.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(ibm_aiops_topo_kafka_incoming_size_bytes_sum{container=\"aiops-topology-topology\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics collected",
   "type": "stat",
   "description": "Refer to the \"Metric Integrations\" component dashboard -> \"Total Metrics Collected\" for further details.\n\nTotal number of metrics collected within the time range across all metric integrations.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated\"}[$__range]) or vector(0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Logs collected",
   "type": "stat",
   "description": "Refer to the \"Log Integrations\" component dashboard -> \"Total Logs Collected\" for further details.\n\nTotal number of logs collected within the time range across all logs integrations.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ibm_aiops_logconnector_custom_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_custom_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_elk_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_elk_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_logscale_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_logscale_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_mezmo_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_mezmo_historical_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_splunk_live_logs_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_logconnector_splunk_historical_logs_data_size_objects_sum[$__range]) or vector(0))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}