- name: be sure App Connect is subscribed
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1alpha1
      group: operators.coreos.com
      kind: Subscription
      metadata:
        name: "{{ ace_package }}"
        namespace: "{{ operator_namespace }}"
      spec:
        name: "{{ ace_package }}"
        installPlanApproval: "{{approval_type}}"
        source: "{{ ace_catalog_name }}"
        sourceNamespace: "{{ ace_catalog_namespace }}"

- name: be sure App Connect is AtLatestKnown
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    name: "{{ ace_package }}"
    namespace: "{{ operator_namespace }}"
    kind: Subscription
  register: acesub_info
  until: 
  - acesub_info.resources is defined
  - acesub_info.resources | length > 0
  - acesub_info.resources[0].status is defined
  - acesub_info.resources[0].status.state is defined
  - acesub_info.resources[0].status.state == "AtLatestKnown"
  retries: 20 # 20 loops at 15 second intervals is 5 minutes 
  delay: 15 # 15 seconds

