apiVersion: batch/v1
kind: Job
metadata:
  name: ia-restore-job
  namespace: velero
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: restore-sa
      volumes:
        - name: restore-data-config
          configMap:
            name: restore-config
        - name: aiops-config
          configMap:
            name: restore-config
        - name: workdir
          emptyDir: {}
      containers:
      - image: "icr.io/cpopen/cp4waiops/cp4waiops-bcdr@sha256:da3581c8047ad07eee1121f98797f52f197eb876dde85fdc96cc56f17783e086"
        imagePullPolicy: Always
        name: ia-restore
        command: ["/bin/bash", "/bcdr/restore/restore.sh","-ia"]
        resources: {}
        env:
        - name: WORKDIR
          value: "/bcdr"
        volumeMounts:
          - name: restore-data-config
            mountPath: /bcdr/restore/restore-data.json
            subPath: restore-data.json 
          - name: aiops-config
            mountPath: /bcdr/common/aiops-config.json
            subPath: aiops-config.json
          - mountPath: /workdir
            name: workdir
      restartPolicy: Never
