language: node_js

dist: jammy

node_js:
- 20

branches:
  only:
    - main
    - sem-test

cache:
  npm: false

before_install:
- cd aiops-cognos-analytics
- npm i -g npm@8
- npm --version

script:
- npm run build
- npm run lint
- npm run test

deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 20
    branch: sem-test
