#!/bin/bash
# The CP4WAIOps status checker tool prints out several components to indicate the status of your install.
# In a successful install, the components below should all have a successful STATUS/PROGRESS/PHASE indicator.
# If any of the components are incomplete or are not reconciled after a significant period of time, 
# please refer to the IBM troubleshooting docs online or open a support case. 

echo "
 __________________________________________________________
|                                                          |
|      CLOUD PAK FOR WATSON AIOPS STATUS CHECKER TOOL      |
|__________________________________________________________|
|  NOTE: Please remember to update the PROJECT_NAMESPACE   |
|  variable in the script so that it correctly references  |
|  your installation namespace.                            |
|                                                          |
|  If this is not set correctly, you will see errors in    |
|  the output of the status checker below.                 |
|                                                          |
|  PROJECT_NAMESPACE by default is set to \"cp4waiops\".     |
|                                                          |
|  If your install is in a namespace called \"cp4waiops\",   |
|  then no change to this script is required.              | 
|                                                          |
|  After running the status checker script, if the         |
|  components listed below have successfully installed,    |
|  each component's Status/Phase will indicate this in     |
|  the list below as Completed/Configured/True/etc.        |
|                                                          |
|  However, if there are components that are not           |
|  fully reconciled yet, please refer to their pod logs    |
|  for more information. If only a short time has passed   |
|  since the install was started, the components may       |
|  need more time to complete fully. If you have waited    |
|  a significant amount of time and the components         |
|  listed below are not indicating completion or success,  |
|  please refer to the troubleshooting docs or open        |
|  a support case.                                         |
|__________________________________________________________|
"
export PROJECT_NAMESPACE="cp4waiops"

# optional argument handling
if [[ "$1" == "version" ]]
then
    echo "0.0.2"
    exit 0
fi

# optional argument handling
if [[ "$1" == "config" ]]
then
    echo "$KUBECONFIG"
    exit 0
fi

# optional argument handling
if [[ "$1" == "status" ]]
then
    echo "______________________________________________________________"
    echo "Installation instances:" && echo ""
    oc get installations.orchestrator.aiops.ibm.com -A 
    
    echo "______________________________________________________________"
    echo "IRCore and AIOpsAnalyticsOrchestrator instances:" && echo ""
    oc get ircore,AIOpsAnalyticsOrchestrator -A  -o custom-columns="KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,VERSION:status.versions.reconciled,STATUS:status.conditions[?(@.type==\"Ready\")].reason"
    
    echo "______________________________________________________________"
    echo "LifecycleService instances:" && echo ""
    oc get lifecycleservice -A -o custom-columns="KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,VERSION:status.versions.reconciled,STATUS:status.conditions[?(@.type==\"Lifecycle Service Ready\")].reason"
    
    echo "______________________________________________________________"
    echo "BaseUI instances:" && echo ""
    oc get BaseUI -A  -o custom-columns="KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,VERSION:status.versions.reconciled,STATUS:status.conditions[?(@.type==\"Ready\")].reason"
    
    echo "______________________________________________________________"
    echo "AIManager, AIOpsEdge, and ASM instances:" && echo ""
    oc get AIManager,aiopsedge,asm -A  -o custom-columns="KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,VERSION:status.versions.reconciled,STATUS:status.phase"
    
    echo "______________________________________________________________"
    echo "AutomationUIConfig, AutomationBase, Cartridge, and CartridgeRequirements instances:" && echo ""
    oc get automationuiconfig,automationbase,cartridge,cartridgerequirements -A -o custom-columns='KIND:.kind,NAMESPACE:.metadata.namespace,NAME:.metadata.name,VERSION:spec.version,STATUS:.status.conditions[?(@.type=="Ready")].status'
    
    echo "______________________________________________________________"
    echo "ZenService instances:" && echo ""
    oc get zenservice -A -o custom-columns='KIND:.kind,NAME:.metadata.name,NAMESPACE:.metadata.namespace,VERSION:status.currentVersion,STATUS:.status.zenStatus,PROGRESS:.status.Progress,MESSAGE:.status.ProgressMessage'
    
    echo "______________________________________________________________"
    echo "CSVs from $PROJECT_NAMESPACE namespace:" && echo ""
    oc get csvs -n $PROJECT_NAMESPACE 
 
    echo "______________________________________________________________"
    echo "CSVs from ibm-common-services namespace:" && echo ""
    oc get csvs -n ibm-common-services

    echo "______________________________________________________________"
    echo "Subscriptions from $PROJECT_NAMESPACE namespace:" && echo ""
    oc get subscriptions -n $PROJECT_NAMESPACE 

    echo "______________________________________________________________"
    echo "Subscriptions from ibm-common-services namespace:" && echo ""
    oc get subscriptions -n ibm-common-services
    
    echo "______________________________________________________________"
    echo "OperandRequest instances:" && echo ""
    oc get operandrequests -A -o custom-columns="NAMESPACE:metadata.namespace,NAME:metadata.name,PHASE:status.phase,CREATED AT:metadata.creationTimestamp"
    
    echo "______________________________________________________________"
    echo "ODLM pod current status:" && echo ""
    oc get pod -n ibm-common-services | grep operand-deployment-lifecycle-manager

    echo "______________________________________________________________"
    echo "Orchestrator pod current status:" && echo ""
    oc get pod -n cp4waiops | grep ibm-aiops-orchestrator-controller-manager
    
    echo ""
    exit 0
fi

echo "kubectl-waiops"
