- name: be sure CatalogSource is installed
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1alpha1
      group: operators.coreos.com
      kind: CatalogSource
      metadata:
        name: "{{ catalog_name }}"
        namespace: "{{ catalog_namespace }}"
      spec:
        sourceType: grpc
        image: "{{ catalog_image }}"

- name: be sure CatalogSource is READY
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    name: "{{ catalog_name }}"
    namespace: "{{ catalog_namespace }}"
    kind: CatalogSource
  register: catalog_info
  until: 
  - catalog_info.resources is defined
  - catalog_info.resources | length > 0
  - catalog_info.resources[0].status is defined
  - catalog_info.resources[0].status.connectionState is defined
  - catalog_info.resources[0].status.connectionState.lastObservedState == "READY"
  retries: 8 # 8 loops at 15 second intervals is 2 minutes 
  delay: 15 # 15 seconds
