{
 "title": "IBM Concert Operate Component - Analytics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Analytics Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Analytics Component\n\nThe Analytics Component is responsible for executing scalable, batch-based data analysis. Using AI-driven policies, it derives actionable insights from alerts and events. These insights include: probable cause determination, temporal correlation between events, seasonality patterns in metrics, anomaly detection in both logs and metrics, and event clustering to identify related incidents. These capabilities enable proactive problem identification and faster incident resolution through automated root cause analysis.\n\nThe component can be broken down further into the following sub-components:\n\n- ***Alert Classifier***: Performs classification of alerts based on their summaries to support downstream automation and decision-making processes.\n- ***Trainer Service***: Handles the scheduling and orchestration of training jobs, ensuring that analytics models are trained efficiently and consistently.\n- ***Spark***: Spark is the compute engine that powers all training jobs within the analytics framework. It enables distributed processing of large-scale data and supports various analytics workloads, including:\n  - Spark Application: A Spark application represents a complete execution of a user-defined analytics job. It includes a driver process and multiple executor processes distributed across the cluster. Each training job—such as temporal correlation, metric anomaly detection, or seasonality analysis—is submitted as a Spark application.\n  - Spark Driver: The driver is the central coordinator of a Spark application. It is responsible for:\n    - Scheduling and distributing tasks across the cluster\n    - Monitoring execution and handling failures\n    - The driver acts as the \"brain\" of the application. If the driver process fails, the entire training job fails, and the Spark job cannot be scheduled or monitored.\n\n- ***Log Anomaly Detection (LAD)***: Logs are ingested from various sources and analyzed for anomalies. Track the normalization of these logs under the LAD section.\n- ***Event Classifier***: Identifies the most important event from a stream of system events. It performs the following functions:\n  - Extracts paths, topological relationships, and event classifications from incoming event data\n  - Computes a criticality score to rank and identify the most significant event within a causal chain or fault domain\n\nDependencies:\n- ***Cassandra***: Cassandra is used as the historical archive for alert data, stored in the aiops.alerts table. It supports efficient long-term storage and retrieval of alerts for training, analysis, and policy generation.\n"
     }
    },
    {
     "title": "Lowest Pod Uptimes",
     "type": "stat",
     "description": "The 5 lowest uptimes within the component pods. Pod restarts can impact functionality, review the pod table and uptime graph for more details.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() -topk(5, sum(kube_pod_start_time{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Analytics Component Pods",
     "type": "table",
     "description": "This panel monitors the status of pods in the Analytics Component of Concert Operate, Pods stuck in \"Pending\" or \"Unknown\" states for prolonged periods of time are problematic and may result in loss of functionality to the component.",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Analytics Component Pods Uptime",
     "type": "timeseries",
     "description": "Pod Uptimes for analytics component pods",
     "gridPos": { "h": 12, "w": 14, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spark Cluster Breakdown",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "options": {
      "content": "#### Training Job: \n- Each training job—such as temporal correlation, metric anomaly detection, or seasonality analysis—is submitted as a Spark application.\n- A Spark application represents a complete execution of a user-defined analytics training job. It includes a driver process and multiple executor processes distributed across the Spark cluster. \n- Failed jobs can be restarted manually but can also be restarted automatically if a schedule is configured. \n#### Spark Driver: \nThe driver is the central coordinator of a Spark application. It is responsible for:\n- Scheduling and distributing tasks across the cluster\n- Monitoring execution and handling failures\n- The driver acts as the \"brain\" of the application. If the driver process fails, the entire job fails. \n"
     }
    },
    {
     "title": "Spark Cluster Status ",
     "type": "stat",
     "description": "This panel shows the status of the Spark cluster used for analytics processing. The metric reports a healthy status when the Spark master node is responsive and at least one worker node is active. If this metric shows unhealthy status, check the Spark cluster health, as this may impact training and analytics capabilities within the Concert Operate platform.\n\n\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ibm_aiops_training_spark_cluster_status",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Alive Spark Worker Nodes",
     "type": "stat",
     "description": "This panel displays the total number of currently active Spark worker nodes in the Concert Operate platform. More alive worker nodes mean a stronger cluster for handling larger jobs. Fewer nodes may indicate resource issues or cluster problems, risking delays or failures.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ibm_aiops_training_spark_cluster_aliveWorkers",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Training Jobs Started",
     "type": "stat",
     "description": "This panel tracks the count of Spark driver submissions, representing the total number of analytics training jobs initiated in the system within the selected time range. Each count increment indicates a new training job has started, regardless of the specific application type.",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "(increase(ibm_aiops_training_spark_driver_submissions_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Training Jobs Completed",
     "type": "stat",
     "description": "This panel shows the number of analytics training jobs that have successfully completed during the selected time period. Each increment represents a Spark driver that has finished its execution with a \"FINISHED\" status, indicating the associated training job completed successfully. Comparing this metric with the total driver submissions helps identify potential issues with training job completion rates and overall analytics system health. Consistently low or dropping numbers may signal job failures, scheduling inefficiencies, or resource issues.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(ibm_aiops_training_spark_cluster_drivers_FINISHED_count[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Failed Spark Drivers",
     "type": "stat",
     "description": "Count of Spark drivers that failed during execution. A low count is expected. High or increasing counts may indicate job failures, scheduling inefficiencies, or resource issues within the Spark cluster. Failed drivers result in incomplete analytics training, which can lead to outdated or missing models for various analytics services. If this metric shows persistent failures, check Spark worker logs, verify memory/CPU allocations, and ensure data sources are accessible.\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_training_spark_cluster_drivers_FAILED_count[$__range]))",
       "legendFormat": "Failed Spark Drivers"
      }
     ]
    },
    {
     "title": "Number of Spark Training Failures (Resource Requirements)",
     "type": "stat",
     "description": "Job submissions failed due to insufficient cluster CPU/memory resources. A low count is expected. High or increasing counts may indicate resource issues, poor workload distribution, or cluster scaling limitations.\n\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_training_spark_lack_of_resource_failure_total[$__range]))",
       "legendFormat": "Failed Spark Training (Resource Failure)"
      }
     ]
    },
    {
     "title": "Number of Spark Drivers Forcibly Killed",
     "type": "stat",
     "description": "Count of manually shut down Spark drivers. A low count is expected, but higher counts may occur during maintenance or when training jobs are intentionally canceled. Frequent unexpected driver kills can interrupt training jobs and prevent model updates. If high counts occur outside maintenance windows, investigate resource constraints or system instability.\n\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_training_spark_cluster_drivers_KILLED_count[$__range]))",
       "legendFormat": "Killed Spark Drivers"
      }
     ]
    },
    {
     "title": "Number of Failed Spark Submissions",
     "type": "stat",
     "description": "Count of failed Spark job submissions. Meaning the jobs couldn't start, often due to Spark driver issues, resource exhaustion, or cluster health problems. Failed submissions prevent analytics models from being trained or updated, potentially leading to outdated anomaly detection capabilities. If this count increases, check Spark cluster health, verify resource availability, and review pod logs for specific error messages.\n\n\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_training_spark_submission_failed_total[$__range]))",
       "legendFormat": "Failed Spark Job Submissions"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Anomaly Detection (LAD)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total logs normalized ",
     "type": "stat",
     "description": "Total number of logs received by the LAD pipeline and normalized with the field mapping set in the log integration UI(s) within the time range.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_splunkmaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_elkmaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_humiomaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_kafkamaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_logdnamaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_custommaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Logs collected per integration ",
     "type": "piechart",
     "description": "Total number of logs collected by each integration within the time range.",
     "gridPos": { "h": 8, "w": 11, "x": 4, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_splunkmaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "Splunk"
      },
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_elkmaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "Elk"
      },
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_humiomaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "Falcon LogScale"
      },
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_kafkamaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "Kafka"
      },
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_logdnamaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "Mezmo"
      },
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_custommaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "Custom log connector"
      }
     ]
    },
    {
     "title": "Splunk logs normalized",
     "type": "stat",
     "description": "Total number of logs received by the LAD pipeline and normalized with the field mapping set in the Splunk integration UI within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_splunkmaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Elk logs normalized",
     "type": "stat",
     "description": "Total number of logs received by the LAD pipeline and normalized with the field mapping set in the Elk integration UI within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_elkmaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Falcon LogScale logs normalized",
     "type": "stat",
     "description": "Total number of logs received by the LAD pipeline and normalized with the field mapping set in the Falcon LogScale integration UI within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_humiomaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bad logs",
     "type": "stat",
     "description": "Percentage of logs filtered out by the LAD pipeline due to: empty messages, json parsing exceptions, template matching exceptions. \n\nIf this percentage is higher than expected, double check your log source is formatting messages properly within the time range. ",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 520 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((sum(increase(ibm_aiops_ladgs_inference_emptymessagefilter_logs_with_empty_messages[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_jsonoptionparser_option_parsing_exception_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_loganomalygoldensignaltemplatematching_gs_template_matching_exception_logs[$__range]) or vector(0)))\n/\nsum(increase(ibm_aiops_ladgs_inference_splunkmaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_elkmaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_humiomaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_kafkamaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_logdnamaplc_normalized_logs[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_ladgs_inference_custommaplc_normalized_logs[$__range]) or vector(0)))\n* 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Kafka logs normalized",
     "type": "stat",
     "description": "Total number of logs received by the LAD pipeline and normalized with the field mapping set in the Kafka integration UI within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 520 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_kafkamaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Mezmo logs normalized",
     "type": "stat",
     "description": "Total number of logs received by the LAD pipeline and normalized with the field mapping set in the Mezmo integration UI within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 520 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_logdnamaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Custom connector logs normalized",
     "type": "stat",
     "description": "Total number of logs received by the LAD pipeline and normalized with the field mapping set in the custom connector integration UI within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 520 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ladgs_inference_custommaplc_normalized_logs[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Classification Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Classifier Breakdown",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
     "options": {
      "content": "This service is used for extraction and classification of the most important event from a stream of system events. It performs the following functions:\n- Extracts paths, topological relationships, and event classifications from incoming event data.\n- Computes a criticality score to rank and identify the most significant event within a causal chain or fault domain.\n\nCassandra serves as the storage layer for the Event Classifier service, storing trained classification models and event criticality data across multiple tenants. It enables the service to maintain historical classification patterns and provides the distributed scalability needed to handle large volumes of event data while ensuring high availability for real-time event importance scoring.\n\n"
     }
    },
    {
     "title": "Cassandra Errors (Total)",
     "type": "stat",
     "description": "This panel shows the total number of failed Cassandra connections and queries in the Event Classifier service of the Concert Operate platform that occurred within the time range. The Event Classifier relies on Cassandra for storing and retrieving event data and model information. Persistent errors can impact event classification accuracy and priority scoring; if errors are detected, check Cassandra pod status, network connectivity, and resource allocation.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_mime_classfier_cassandra_errors_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed HTTP Requests",
     "type": "stat",
     "description": "This panel displays the total number of failed HTTP requests in the Event Classifier service of the Concert Operate platform. The Event Classifier makes HTTP requests to communicate with other services or external APIs. Failures here can prevent alerts/incidents from recieving the appropriate insights such as temporal correlation or seasonality. Review the component pods for specific error messages.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_mime_classfier_http_requests_errors_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Errors",
     "type": "stat",
     "description": "This panel displays the total number of failed Kafka connections in the Event Classifier service of the Concert Operate platform. The Event Classifier relies on Kafka for ingesting and processing system events. A consistently high number of failed connections might indicate network issues, misconfigurations, or problems with Kafka. Persistent errors can lead to missed critical events and incomplete event classification; if errors occur, check Kafka broker pod status, verify broker connectivity, and ensure proper topic configurations are in place.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_mime_classfier_kafka_errors_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "gauge",
     "description": "The Event Classifier service disk usage refers to the sizing of the classifier models and logging. If usage is above healthy thresholds, determine the sizing of trained data. High usage should be monitored to ensure the Event Classifier functionality is not interrupted.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_mime_classfier_disk_usage{generation=\"used\"})/sum(ibm_aiops_mime_classfier_disk_usage{generation=\"total\"})*100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": " API Overview",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "options": {
      "content": "- #### Metric Retrieval API: \n  - Purpose: Allows querying and retrieving metric values from the system\n  - Usage: Used to access historical and current metric data for analysis and visualization\n\n- #### Metric Types API: \n  - Purpose: Provides information about available metric types, groups, and resources\n  - Usage: Used to discover what metrics are available in the system and their structure\n\n- #### Metric Forecast API: \n  - Purpose: Generates predictive forecasts for metric values based on historical data\n  - Usage: Used to predict future metric trends and potential anomalies\n\n- #### Blocked API Service: \n  - Purpose: Manages the blocklist of resources to exclude from data collection\n  - Usage: Primarily used in POC environments to reduce data volume on smaller systems\n\n- #### Purge API: \n  - Purpose: Triggers removal of data associated with blocklisted resources\n  - Usage: Cleans up data storage by removing metrics from blocklisted resources\n\n- #### Metric Retrieval API: \n  - Purpose: Allows querying and retrieving metric values from the system\n  - Usage: Used to access historical and current metric data for analysis and visualization\n\n- #### Service Monitor API: \n  - Purpose: Internal health check mechanism for the metrics subsystem\n  - Usage: Used by dependent services to verify metrics system availability\n"
     }
    },
    {
     "title": "API Ingestion Latency (Median Performance - p50)",
     "type": "timeseries",
     "description": "Tracks the p50 over time of API operations computed at 10 minute intervals. Used to monitor the performance and responsiveness of metric processing.\n\np50 - shows typical performance. p50 = 1 second means half of all requests occurred in 1 second or less.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ibm_aiops_metric_api_BlockedApi_metric_ingestion_timed{quantile=\"0.5\"}",
       "legendFormat": "Blocked API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricIngestionApi_metric_ingestion_timed{quantile=\"0.5\"}",
       "legendFormat": "Metric Ingestion API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricIngestionApi_metricz_ingestion_timed{quantile=\"0.5\"}",
       "legendFormat": "MetricZ Ingestion API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricRetrievalApi_metric_forecast_timed{quantile=\"0.5\"}",
       "legendFormat": "Metric Retrieval (forecast) API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricRetrievalApi_metric_retrieval_timed{quantile=\"0.5\"}",
       "legendFormat": "Metric Retrieval API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricTypesApi_metric_ingestion_timed{quantile=\"0.5\"}",
       "legendFormat": "Metric Types (Metric Ingestion) API"
      },
      {
       "expr": "ibm_aiops_metric_api_PurgeApi_metric_ingestion_timed{quantile=\"0.5\"}",
       "legendFormat": "Purge (Metric Ingestion) API"
      },
      {
       "expr": "ibm_aiops_metric_api_com_ibm_itsm_servicemonitor_api_ServiceMonitorApi_itsm_servicemonitor_consolidate_timed{quantile=\"0.5\"}",
       "legendFormat": "Service Monitor API"
      },
      {
       "expr": "ibm_aiops_metric_api_metric_ingestion_kafka_publish_latency{quantile=\"0.5\"}",
       "legendFormat": "Kafka (metric) Publish API"
      },
      {
       "expr": "ibm_aiops_metric_api_metricz_ingestion_kafka_publish_latency{quantile=\"0.5\"}",
       "legendFormat": "Kafka (MetricZ) Publish API"
      }
     ]
    },
    {
     "title": "API Ingestion Latency (Tail Latency - p99)",
     "type": "timeseries",
     "description": "Tracks the p99 over time for API operations computed at 10 minute intervals. Used to monitor the performance and responsiveness of metric processing.\np99 - gives insight into slowest response times. p99 = 1 second means 99% of all requests occurred in 1 second or less.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ibm_aiops_metric_api_BlockedApi_metric_ingestion_timed{quantile=\"0.99\"}",
       "legendFormat": "Blocked API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricIngestionApi_metric_ingestion_timed{quantile=\"0.99\"}",
       "legendFormat": "Metric Ingestion API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricIngestionApi_metricz_ingestion_timed{quantile=\"0.99\"}",
       "legendFormat": "MetricZ Ingestion API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricRetrievalApi_metric_forecast_timed{quantile=\"0.99\"}",
       "legendFormat": "Metric Retrieval (forecast) API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricRetrievalApi_metric_retrieval_timed{quantile=\"0.99\"}",
       "legendFormat": "Metric Retrieval API"
      },
      {
       "expr": "ibm_aiops_metric_api_MetricTypesApi_metric_ingestion_timed{quantile=\"0.99\"}",
       "legendFormat": "Metric Types (Metric Ingestion) API"
      },
      {
       "expr": "ibm_aiops_metric_api_PurgeApi_metric_ingestion_timed{quantile=\"0.99\"}",
       "legendFormat": "Purge (Metric Ingestion) API"
      },
      {
       "expr": "ibm_aiops_metric_api_com_ibm_itsm_servicemonitor_api_ServiceMonitorApi_itsm_servicemonitor_consolidate_timed{quantile=\"0.99\"}",
       "legendFormat": "Service Monitor API"
      },
      {
       "expr": "ibm_aiops_metric_api_metric_ingestion_kafka_publish_latency{quantile=\"0.99\"}",
       "legendFormat": "Kafka (metric) Publish API"
      },
      {
       "expr": "ibm_aiops_metric_api_metricz_ingestion_kafka_publish_latency{quantile=\"0.99\"}",
       "legendFormat": "Kafka (MetricZ) Publish API"
      }
     ]
    },
    {
     "title": "API Exceptions",
     "type": "stat",
     "description": "This panel visualizes the total number of exceptions raised on requests across various APIs/services in the Analytics component over a specified time range. \nExceptions can lead to gaps in functionality, review the component pod health as a starting point. If pod uptime and resource usage are healthy, review their logs for any visible exceptions. \n\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_training_rest_BatchTrainingServiceApi_batch_training_exceptionmetered_exceptions_total[$__range]))",
       "legendFormat": "Batch Training API"
      },
      {
       "expr": "sum(increase(ibm_aiops_training_rest_ConfigurationServiceApi_configurations_exceptionmetered_exceptions_total[$__range]))",
       "legendFormat": "Configuration Service API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_com_ibm_itsm_servicemonitor_api_ServiceMonitorApi_itsm_servicemonitor_consolidate_exceptionmetered_exceptions_total[$__range]))",
       "legendFormat": "Service Monitor API"
      },
      {
       "expr": "sum(increase(ibm_aiops_training_rest_ScheduleServiceApi_schedules_exceptionmetered_exceptions_total[$__range]))",
       "legendFormat": "Scheduler Service API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_MetricRetrievalApi_metric_forecast_exceptionmetered_exceptions_total[$__range])) + sum(increase(ibm_aiops_metric_api_metric_forecast_api_failures_total[$__range]))",
       "legendFormat": "Metric Forecast API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_MetricIngestionApi_metric_ingestion_exceptionmetered_exceptions_total[$__range])) + sum(increase(ibm_aiops_metric_api_metric_ingestion_api_failures_total[$__range]))",
       "legendFormat": "Metric Ingestion API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_BlockedApi_metric_ingestion_exceptionmetered_exceptions_total[$__range]))",
       "legendFormat": "Blocked API Service"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_MetricRetrievalApi_metric_retrieval_exceptionmetered_exceptions_total[$__range])) + sum(increase(ibm_aiops_metric_api_metric_retrieval_api_failures_total[$__range]))",
       "legendFormat": "Metric Retrieval API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_MetricIngestionApi_metricz_ingestion_exceptionmetered_exceptions_total[$__range])) + sum(increase(ibm_aiops_metric_api_metricz_ingestion_api_failures_total[$__range]))",
       "legendFormat": "Metric Z Ingestion API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_MetricTypesApi_metric_ingestion_exceptionmetered_exceptions_total[$__range]))",
       "legendFormat": "Metric Types API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_MetricTypesApi_metric_ingestion_exceptionmetered_exceptions_total[$__range]))",
       "legendFormat": "Purge API"
      },
      {
       "expr": "sum(increase(ibm_aiops_training_rest_BatchTrainingServiceApi_batch_training_status_exceptionmetered_exceptions_total[$__range]))",
       "legendFormat": "Batch Training Status API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_metricz_ingestion_kafka_publish_failures_total[$__range]))",
       "legendFormat": "MetricZ Ingestion Kafka Publish"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_metric_ingestion_kafka_publish_failures_total[$__range]))",
       "legendFormat": "Metric Ingestion Kafka Publish"
      }
     ]
    },
    {
     "title": "API Requests Across Services",
     "type": "stat",
     "description": "This panel visualizes the total number of API requests observed across various APIs in the Concert Operate platform over a specified time range. A consistently high number of API instances or operations might indicate increased workload, potential performance bottlenecks, or the need for additional resources.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metric_api_metric_forecast_api_requests_total[$__range]))",
       "legendFormat": "Metric Forecast API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_metric_ingestion_api_requests_total[$__range]))",
       "legendFormat": "Metric Ingestion API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_metricz_ingestion_api_requests_total[$__range]))",
       "legendFormat": "Metric Z Ingestion API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_metric_retrieval_api_requests_total[$__range]))",
       "legendFormat": "Retrieval API"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_metricz_ingestion_kafka_publish_count_total[$__range]))",
       "legendFormat": "Kafka Publish (MetricZ)"
      },
      {
       "expr": "sum(increase(ibm_aiops_metric_api_metric_ingestion_kafka_publish_count_total[$__range]))",
       "legendFormat": "Kafka Publish "
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\"aiops-ir-analytics-.*|aiops-lad-flink.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Spark Master Node CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Spark Master pod in the Analytics component. High CPU usage may indicate that the Spark Master pod are under heavy load, potentially impacting analytics execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of analytics tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*spark-master.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*spark-master.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*spark-master.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Spark Master Node Memory  Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Spark Master Node pods in the Analytics component. High memory usage may indicate that the Spark Master Node  are consuming significant resources, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.\n\n\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*spark-master.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*spark-master.*\", resource=\"memory\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*spark-master.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Spark Worker CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Spark Workers in the Analytics component. High CPU usage may indicate that the Spark Workers are under heavy load, potentially impacting analytics execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of analytics tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*spark-worker.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*spark-worker.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*spark-worker.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Spark Worker Memory  Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Spark Workers pods in the Analytics component. High memory usage may indicate that the Spark Workers are consuming significant resources, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.\n\n\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*spark-worker.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*spark-worker.*\", resource=\"memory\"}) ",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*spark-worker.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Spark Pipeline Composer CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Spark Pipeline Composer in the Analytics component. High CPU usage may indicate that the Spark Pipeline Composer is under heavy load, potentially impacting analytics execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of analytics tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*spark-pipeline-composer.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*spark-pipeline-composer.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*spark-pipeline-composer.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Spark Pipeline Composer Memory  Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Spark Pipeline Composer pods in the Analytics component. High memory usage may indicate that the Spark Pipeline Composer is consuming significant resources, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.\n\n\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*spark-pipeline-composer.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*spark-pipeline-composer.*\", resource=\"memory\"}) ",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*spark-pipeline-composer.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Classifier CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Classifier Service in the Analytics component. High CPU usage may indicate that the Classifier Service pod is under heavy load, potentially impacting analytics execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of analytics tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-ir-analytics-classifier-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-classifier-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-classifier-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"})",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Classifier Memory  Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Classifier Service pods in the Analytics component. High memory usage may indicate that the Classifier Service are consuming significant resources, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.\n\n\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-ir-analytics-classifier-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-classifier-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-classifier-.*\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Metric Action CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Metric Action pods in the Analytics component. High CPU usage may indicate that the Metric Action pod is under heavy load, potentially impacting analytics execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of analytics tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-ir-analytics-metric-action-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-metric-action-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-metric-action-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Metric Action Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Metric Action  pods in the Analytics component. High memory usage may indicate that the Metric Action  are consuming significant resources, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.\n\n\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-ir-analytics-metric-action-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-metric-action-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-metric-action-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Metric API CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Metric API pods in the Analytics component. High CPU usage may indicate that the Metric API pod is under heavy load, potentially impacting analytics execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of analytics tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-ir-analytics-metric-api-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-metric-api-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-metric-api-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Metric API Memory  Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Metric API  pods in the Analytics component. High memory usage may indicate that the Metric API  are consuming significant resources, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.\n\n\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-ir-analytics-metric-api-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-metric-api-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-metric-api-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Metric Spark CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Metric Spark pods in the Analytics component. High CPU usage may indicate that the Metric Spark pod is under heavy load, potentially impacting analytics execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of analytics tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-ir-analytics-metric-spark-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-metric-spark-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-metric-spark-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Metric Spark Memory  Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Metric Spark  pods in the Analytics component. High memory usage may indicate that the Metric Spark  are consuming significant resources, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.\n\n\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-ir-analytics-metric-spark-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-metric-spark-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-metric-spark-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Probable Cause CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Probable Cause pods in the Analytics component. High CPU usage may indicate that the Probable Cause pod is under heavy load, potentially impacting analytics execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of analytics tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-ir-analytics-probablecause-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-probablecause-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-probablecause-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Probable Cause Memory  Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Probable Cause  pods in the Analytics component. High memory usage may indicate that the Probable Cause  are consuming significant resources, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.\n\n\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-ir-analytics-probablecause-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-ir-analytics-probablecause-.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-ir-analytics-probablecause-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "LAD Jobmanager CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of the LAD Manager in the Analytics component. High CPU usage may indicate that the Job Manager is under heavy load, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*lad-flink-.*\", pod!~\".*lad-flink-taskmanager.*\", container!=\"\", container!=\"POD\", container=~\"flink-main-container\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*lad-flink-.*\", pod!~\".*lad-flink-taskmanager.*\", container!=\"\", container!=\"POD\", container=~\"flink-main-container\", resource=\"cpu\"}) ",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*lad-flink-.*\", pod!~\".*lad-flink-taskmanager.*\", container!=\"\", container!=\"POD\", container=~\"flink-main-container\", resource=\"cpu\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "LAD Jobmanager Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Job Manager pods in the Analytics component. High memory usage may suggest that the Job Managers are consuming significant resources, potentially affecting policy execution performance. Monitor this metric to ensure efficient resource allocation and optimal processing of policy tasks.\n\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*lad-flink-.*\", pod!~\".*lad-flink-taskmanager.*\", container=~\"flink-main-container\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*lad-flink-.*\", pod!~\".*lad-flink-taskmanager.*\", container=~\"flink-main-container\", container!=\"\", container!=\"POD\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*lad-flink-.*\", pod!~\".*lad-flink-taskmanager.*\", container=~\"flink-main-container\", container!=\"\", container!=\"POD\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "LAD Taskmanager CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of the LAD Manager in the Analytics component. High CPU usage may indicate that the Job Manager is under heavy load, potentially impacting policy execution performance. Monitor this metric to ensure optimal resource allocation and efficient processing of policy tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*lad-flink-taskmanager.*\", container!=\"\", container!=\"POD\", container=~\"flink-main-container\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*lad-flink-taskmanager.*\", container!=\"\", container!=\"POD\", container=~\"flink-main-container\", resource=\"cpu\"}) ",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*lad-flink-taskmanager.*\", container!=\"\", container!=\"POD\", container=~\"flink-main-container\", resource=\"cpu\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "LAD Taskmanager Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the working set memory usage of Task Manager pods in the Analytics component. High memory usage may suggest that the Task Managers are consuming significant resources, potentially affecting policy execution performance. Monitor this metric to ensure efficient resource allocation and optimal processing of policy tasks.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*lad-flink-taskmanager.*\", container=~\"flink-main-container\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*lad-flink-taskmanager.*\", container=~\"flink-main-container\", container!=\"\", container!=\"POD\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*lad-flink-taskmanager.*\", container=~\"flink-main-container\", container!=\"\", container!=\"POD\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    }
   ]
  }
 ]
}