{
 "title": "ServiceNow Integration",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "ServiceNow integration Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# ServiceNow integration\n\n**Ticket creation flow**:  \n1. **ChatOps orchestrator:** Formats ServiceNow payload (gathers alerts, applies mapping) and pushes it into kafka for the snow connector to consume.\n2. **grpc snow connector:** Consumes the snow payload via kafka and makes the api call to ServiceNow. Pushes the response from ServiceNow into kafka.\n3. **ChatOps orchestrator:** Consumes the response via kafka and persists the ServiceNow permalink onto the incident for the UI to display.\n"
     }
    },
    {
     "title": "Lowest Pod Uptimes",
     "type": "stat",
     "description": "The 5 lowest uptimes within the component pods. Pod restarts can impact functionality, review the pod table and uptime graph for more details.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() -topk(5, sum(kube_pod_start_time{pod=~\".*chatops-orch.*|.*grpc-snow.*|\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ServiceNow integration Component Pods",
     "type": "table",
     "description": "This panel displays the number of active pods for all defined ServiceNow integration pods. Pods stuck in \"Pending\" or \"Unknown\" states for prolonged periods of time are problematic and may result in loss of functionality.",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ServiceNow integration Component Pods Uptime",
     "type": "timeseries",
     "description": "Pod uptimes for ServiceNow integration",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\".*chatops-orch.*|.*grpc-snow.*|\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Resource Utlization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "stat",
   "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*chatops-orch.*|.*grpc-snow.*|\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ChatOps orchestrator CPU Usage ",
   "type": "timeseries",
   "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*chatops-orch.*\"}) by (pod)",
     "legendFormat": "usage - {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~\".*chatops-orch.*\", resource=\"cpu\"})",
     "legendFormat": "requests "
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\".*chatops-orch.*\", resource=\"cpu\"}) ",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "ChatOps orchestrator Memory Usage ",
   "type": "timeseries",
   "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\".*chatops-orch.*\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "usage - {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~\".*chatops-orch.*\", resource=\"memory\"}) ",
     "legendFormat": "requests "
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\".*chatops-orch.*\", resource=\"memory\"}) ",
     "legendFormat": "limits "
    }
   ]
  },
  {
   "title": "Snow connector CPU Usage ",
   "type": "timeseries",
   "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*snow-conn.*\"}) by (pod)",
     "legendFormat": "usage - {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~\".*snow-conn.*\", resource=\"cpu\"})",
     "legendFormat": "requests "
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\".*snow-conn.*\", resource=\"cpu\"}) ",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Snow connector Memory Usage ",
   "type": "timeseries",
   "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\".*snow-conn.*\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "usage - {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~\".*snow-conn.*\", resource=\"memory\"}) ",
     "legendFormat": "requests "
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\".*snow-conn.*\", resource=\"memory\"}) ",
     "legendFormat": "limits "
    }
   ]
  }
 ]
}