{
 "title": "IBM Concert Operate Component - Event Integrations",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Event Integration Component Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Integrations Overview",
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "## Event Connectors Overview\nThe Event Integrations are critical components of the Concert Operate platform, responsible for ingesting, normalizing, and forwarding event data from various sources into the system for analysis and correlation. These integrations serve as the primary entry points for operational events that drive incident detection and resolution.\n\n- Netcool Integration: Synchronizes event data from IBM Netcool Operations Insight ObjectServer with Concert Operate. Each ObjectServer pair requires a separate Netcool integration to ensure complete event coverage across the monitoring infrastructure.\n- Instana Integration: Provides event data from Instana's application performance monitoring platform, enabling the analysis and processing of different types of alerts and events. This integration is crucial for incorporating application-level incidents into the broader operational context.\n- Generic WebHook Integration: Is used when you want to connect to a data source and a dedicated integration is not available for that source in the IBM Concert Operate Integrations UI, you can use the generic webhook integration. There exists an internal wehbook connection for self monitoring. \n\nIntegrations perform several key functions:\n- Event normalization and transformation to a common format\n- Filtering and enrichment of event data\n- Secure transmission of events to the Concert Operate platform\n- Maintaining state and ensuring delivery reliability\n\nThe health and performance of these integrations directly impact the platform's ability to detect, analyze, and respond to incidents across the monitored environment. Monitoring their operational status is essential for ensuring complete visibility into the event landscape."
     }
    },
    {
     "title": "Lowest Pod Uptimes",
     "type": "stat",
     "description": "The 5 lowest uptimes within the component pods. Pod restarts can impact functionality, review the pod table and uptime graph for more details.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() -topk(5, sum(kube_pod_start_time{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*|.*-webhook-connector-.*\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Integrations Pods",
     "type": "table",
     "description": "This panel monitors the status of pods in the Event Integration Component of Concert Operate, Pods stuck in \"Pending\" or \"Unknown\" states for prolonged periods of time are problematic and may result in loss of functionality to the component. ",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*|.*-webhook-connector-.*\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Integration Pods Uptime",
     "type": "timeseries",
     "description": "Pod Uptimes for Event Integration component pods\n\n",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*|.*-webhook-connector-.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "(Event) Netcool Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netcool Dropped Kafka Messages",
     "type": "stat",
     "description": "This panel tracks Kafka messages that were received by Netcool Integrations but could not be properly deserialized or processed, resulting in data loss. Non-zero values indicate potential issues with message format compatibility, serialization errors, or corrupt data that may impact the completeness of information flowing through the system. If dropped messages are detected, check connector logs for deserialization errors and verify that message producers are generating correctly formatted data.\n\n\n",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(connector_sdk_kafka_consumer_dropped_total{pod=~\"netcool-conn-.*\"}[$__range])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netcool Exceptions",
     "type": "stat",
     "description": "This panel tracks internal exceptions thrown by Netcool Integrations during data collection and processing operations. Non-zero values indicate functional failures that may impact data completeness or accuracy, requiring investigation of connector logs for specific error details. If exceptions persist, check the connector's configuration, verify endpoint accessibility, and ensure sufficient resources are allocated to connector pods.\n\n\n",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(connectors_sdk_connectorexceptions_thrown_total{pod=~\"netcool-conn-.*\"}[$__range])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netcool  Status Failures",
     "type": "stat",
     "description": "This panel tracks status communication failures between Netcool connectors and the connector-bridge pod, indicating instances where connectors may be functioning but unable to report their health status. When values are non-zero, check network connectivity, certificate validity, and the connector-bridge pod's health, as these failures can cause connectors to incorrectly appear as \"Down\" or \"Unknown\" in the management interface. Most issues can be resolved by addressing network problems or restarting the affected connectors.\n\n\n",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(connector_sdk_status_failed_total{pod=~\"netcool-conn-.*\"}[$__range])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netcool Actions Messaging Processing Rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of netcool actions messages over 3m averages. \n",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(aiops_connector_messages_action_processed_total{container=\"netcool-connector\"}[3m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netcool Actions Message Processing Count",
     "type": "stat",
     "description": "This panel tracks the count of connector action messages processed within the time range, per Netcool connector. Healthy systems show consistent rates matching typical workloads, while sudden drops or spikes may indicate connector failures or backlogs.\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(aiops_connector_messages_action_processed_total{container=\"netcool-connector\"}[$__range])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netcool Messaging Processing Rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of netcool messaging over 3m averages. \n",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(aiops_connector_messages_processed_total{container=\"netcool-connector\"}[3m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netcool Message Processing Count",
     "type": "stat",
     "description": "This panel tracks the count of messages processed within the time range, per Netcool Integration. Consistent patterns indicate healthy data flow, while sudden drops may signal connector failures affecting incident detection.\n\n\n\n\n\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(aiops_connector_messages_processed_total{container=\"netcool-connector\"}[$__range])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netcool Alerts Emitted Rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of alerts emitted by netcool connector over 3m averages. \n",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(aiops_connector_netcool_events_emitted_total[3m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netcool Alerts Emitted",
     "type": "stat",
     "description": "This panel tracks alerts emitted within the time range, per Netcool Integration. Consistent emission patterns indicate healthy integration, while drops may signal failures affecting alert delivery.\n\n\n\n\n\n\n\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(aiops_connector_netcool_events_emitted_total[$__range])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "(Event) Instana Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instana Dropped Kafka Messages",
     "type": "stat",
     "description": "This panel tracks Kafka messages that were received by Instana Integrations but could not be properly deserialized or processed, resulting in data loss. Non-zero values indicate potential issues with message format compatibility, serialization errors, or corrupt data that may impact the completeness of information flowing through the system. If dropped messages are detected, check integration pod  logs for deserialization errors and verify that message producers are generating correctly formatted data.\n\n\n\n\n\n\n\n\n\n",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(connector_sdk_kafka_consumer_dropped_total{pod=~\".*-instana-.*\"}[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Instana Exceptions",
     "type": "stat",
     "description": "This panel tracks internal exceptions thrown by Instana Integrations during data collection and processing operations. Non-zero values indicate functional failures that may impact data completeness or accuracy, requiring investigation of connector logs for specific error details. If exceptions persist, check the connector's configuration, verify endpoint accessibility, and ensure sufficient resources are allocated to connector pods.\n\n\n\n\n\n",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(connectors_sdk_connectorexceptions_thrown_total{pod=~\".*-instana-.*\"}[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Instana Status Failures",
     "type": "stat",
     "description": "This panel tracks status communication failures between Instana Integrations and the connector-bridge pod that occurred within the time range. These failures indicate instances where integrations may be functioning but are unable to report their health status. When values are non-zero, check network connectivity, certificate validity, and the connector-bridge pod's health, as these failures can cause integrations to incorrectly appear as \"Down\" or \"Unknown\" in the management interface. Most issues can be resolved by addressing network problems or restarting the affected integrations.\n",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(connector_sdk_status_failed_total{pod=~\".*-instana-.*\"}[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Instana Event/Alert Ingestion Rates by Pod",
     "type": "timeseries",
     "description": "Shows the per-second rate for incoming events and alert create/update messages over 3m averages ingested from Instana. \n",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum (rate(connector_cloudevents_emitted_total{channel_name=\"cp4waiops-cartridge.lifecycle.input.events\", component_name=\"instana\"}[3m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Instana Event/Alert Message Count",
     "type": "stat",
     "description": "This panel tracks the count of event/alert messages ingested by each Instana integration within the given time range. Consistent data flow in indicates healthy data collection and processing, while drops may indicate integration issues affecting ingestion.\n\n\n\n\n\n\n\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum(increase(connector_cloudevents_emitted_total{channel_name=\"cp4waiops-cartridge.lifecycle.input.events\", component_name=\"instana\"}[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Instana API Data Transfer Volume by Pod",
     "type": "timeseries",
     "description": "Shows the per-second rate for data transferred through integration over 3m averages by Instana Integration pods. \n\n\n\n\n\n\n\n\n\n",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum(rate(aiops_connector_api_calls_kilobytes_sum{component_name=\"instana\"}[3m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Instana API Data Transfer Volume",
     "type": "stat",
     "description": "This panel shows aggregate data transferred through integration APIs.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(aiops_connector_api_calls_kilobytes_sum{component_name=\"instana\"}[$__range])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "(Event) WebHook Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "WebHook Exceptions",
     "type": "stat",
     "description": "This panel tracks internal exceptions thrown by WebHook Integrations during data collection and processing operations. Non-zero values indicate functional failures that may impact data completeness or accuracy, requiring investigation of integrations logs for specific error details. If exceptions persist, check the integration's configuration, verify endpoint accessibility, and ensure sufficient resources are allocated to integration pods.\n\n\n\n\n\n",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum(increase(connectors_sdk_connectorexceptions_thrown_total{pod=~\".*-webhook-.*\"}[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WebHook Status Failures",
     "type": "stat",
     "description": "This panel tracks status communication failures between WebHook Integrations and the connector-bridge pod, indicating instances where integrations may be functioning but unable to report their health status. When values are non-zero, check network connectivity, certificate validity, and the connector-bridge pod's health, as these failures can cause connectors to incorrectly appear as \"Down\" or \"Unknown\" in the management interface. Most issues can be resolved by addressing network problems or restarting the affected integrations.\n\n\n",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "sum(increase(connector_sdk_status_failed_total{pod=~\".*-webhook-.*\"}[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utlization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\"netcool-conn-.*|ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Netcool Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Netcool Integration pod. High CPU usage may indicate that the Netcool Integration pods are under heavy load, potentially impacting event ingestion and synchronization performance. Monitor this metric to ensure optimal resource allocation and efficient processing of integration tasks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"netcool-conn-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"netcool-conn-.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"netcool-conn-.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Netcool Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second Memory usage rate of Netcool Integration pod. High Memory usage may indicate that the Netcool Integration pods are consuming significant resources. Monitor this metric to ensure optimal resource allocation and efficient processing of integration tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"netcool-conn-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"netcool-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"netcool-conn-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Instana Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Instana Integration pod. High CPU usage may indicate that the Instana Integration pods are under heavy load, potentially impacting event ingestion and synchronization performance. Monitor this metric to ensure optimal resource allocation and efficient processing of integration tasks\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ibm-grpc-instana-connector-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-grpc-instana-connector-.*\", resource=\"cpu\"}) ",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-grpc-instana-connector-.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Instana Connector Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second Memory usage rate of Instana Integration pod. High Memory usage may indicate that the Instana Integration pods are consuming significant resources. Monitor this metric to ensure optimal resource allocation and efficient processing of integration tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"ibm-grpc-instana-connector-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-grpc-instana-connector-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-grpc-instana-connector-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Webhook Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second CPU usage rate of Webhook Integration pod. High CPU usage may indicate that the Webhook Integration pods are under heavy load, potentially impacting event ingestion and synchronization performance. Monitor this metric to ensure optimal resource allocation and efficient processing of integration tasks\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ibm-grpc-webhook-connector-.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-grpc-webhook-connector-.*\", resource=\"cpu\"}) ",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-grpc-webhook-connector-.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Webhook Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the per-second Memory usage rate of Webhook Integration pod(s). High Memory usage may indicate that the Webhook Integration pods are consuming significant resources. Monitor this metric to ensure optimal resource allocation and efficient processing of integration tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"ibm-grpc-webhook-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"ibm-grpc-webhook-.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"ibm-grpc-webhook-.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    }
   ]
  }
 ]
}