{
 "title": "IBM Concert Operate - Usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Objective",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
     "options": {
      "content": "# Objective\nThe goal of this dashboard is to provide visibility\n on the level of traffic flowing through the \n environment and make sure that Cloud Pak for\n  Concert Operate is properly configured to handle it\n  as described in the [sizing documentation](https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/4.6.1?topic=planning-hardware-requirements#aimgr_custom). "
     }
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event ingestion rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of events ingested into the system over 3m averages. \n\nKafka topic: cp4waiops-cartridge.lifecycle.input.events ",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.lifecycle.input.events\"}[3m]))",
       "legendFormat": "New events"
      }
     ]
    },
    {
     "title": "Events ingested in time range",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.lifecycle.input.events\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alert request rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of alert create/update requests over 3m averages. \n\nKafka topic: cp4waiops-cartridge.irdatalayer.changes.alerts",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.alerts\"}[3m]))",
       "legendFormat": "Alert creates & updates"
      }
     ]
    },
    {
     "title": "Alerts created/updated in time range",
     "type": "stat",
     "description": "Count that tracks alert create/update requests in time range. Updates can come from events, manual user changes, and Concert Operate enrichments.",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.alerts\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Incidents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incident request rates",
     "type": "timeseries",
     "description": "Shows the per-second rate of incident create/update requests over 3m averages. \n\nKafka topic: cp4waiops-cartridge.irdatalayer.changes.stories",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.stories\"}[3m]))",
       "legendFormat": "Incident creates/updates"
      }
     ]
    },
    {
     "title": "Incidents created/updated in time range",
     "type": "stat",
     "description": "Count that tracks incident create/update requests in time range. Updates can come from alerts, manual user changes, and IBM Concert Operate enrichments.",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.stories\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of logs ingested into the system over 1m averages. Log integrations can be created in the Concert Operate integrations page.\n\nKafka topic: cp4waiops-cartridge-logs-.*-raw",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge-logs-.*-raw\"}[1m]))",
       "legendFormat": "Incoming logs"
      }
     ]
    },
    {
     "title": "Logs ingested in time range",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge-logs-.*-raw\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of metrics ingested into the system over 3m averages. Metric integrations can be created in the IBM Concert Operate integrations page.\n\nKafka topic: cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "metrics/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated\"}[3m]))",
       "legendFormat": "Incoming metrics"
      }
     ]
    },
    {
     "title": "Metrics ingested in time range",
     "type": "stat",
     "description": "Count of metrics ingested within the time range. Metric integrations can be created in the IBM Concert Operate integrations page.\n\nTo view an accurate count, select a time window that is equal to, or longer than the metric aggregation interval . For example, if the aggregation interval is 5 minutes, select a time window from the time picker that is at least 5 minutes long. The aggregation interval is viewable and configurable in the IBM Concert Operate integrations page.\n\nKafka topic: cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Runbooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runbook execution rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of runbooks executed in the system over 1m averages. Runbooks can be created and configured under the Concert Operate Automations page.\n\nKafka topic: cp4waiops-cartridge.lifecycle.output.rba-exec-requests",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "executions/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.lifecycle.output.rba-exec-requests\"}[3m]))",
       "legendFormat": "Runbook executions"
      }
     ]
    },
    {
     "title": "Runbooks executed in time range",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.lifecycle.output.rba-exec-requests\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ServiceNow Incidents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rates",
     "type": "timeseries",
     "description": "Time series that tracks the ServiceNow request rates per minute for:\n* incidents create/updates\n* alerts updates\n* change risk assessments\n\nThis does not include requests made for polling. Those requests are made at consistent, configurable intervals that can be set in the IBM Concert Operate ServiceNow integration.",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum((rate(snow_incident_create_action_total[3m]) * 60) or vector(0))",
       "legendFormat": "servicenow incident create/update requests"
      },
      {
       "expr": "sum((rate(snow_incident_create_action_error_total[3m]) * 60) or vector(0))",
       "legendFormat": "servicenow incident create/update errors"
      },
      {
       "expr": "sum((rate(snow_alert_update_action_total[3m]) * 60) or vector(0))",
       "legendFormat": "servicenow alert update requests"
      },
      {
       "expr": "sum((rate(snow_alert_update_action_error_total[3m]) * 60) or vector(0))",
       "legendFormat": "servicenow alert update errors"
      },
      {
       "expr": "sum((rate(snow_comment_create_action_total[3m]) * 60) or vector(0))",
       "legendFormat": "servicenow change risk assessment requests"
      },
      {
       "expr": "sum((rate(snow_comment_create_action_error_total[3m]) * 60) or vector(0))",
       "legendFormat": "servicenow change risk assessment errors"
      }
     ]
    },
    {
     "title": "ServiceNow Incident create/update requests",
     "type": "stat",
     "description": "Count that tracks incident create/update requests sent to ServiceNow within the time range. Subtract (Incident create/update failures) from this number to calculate the number of successful requests.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 42 },
     "targets": [
      {
       "expr": "sum(increase(snow_incident_create_action_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ServiceNow incident create/update errors",
     "type": "stat",
     "description": "Count that tracks incident create/update requests sent to ServiceNow that resulted in an error within the time range. \n\nFailures could be due to lack of permissions, check that the integration user has the appropriate roles: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/latest?topic=integrations-servicenow-app-integration#create_roles ",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 46 },
     "targets": [
      {
       "expr": "sum(increase(snow_incident_create_action_error_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Github issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rates",
     "type": "timeseries",
     "description": "Time series that tracks the request rates per minute for:\n* Issue creation requests/success/failure\n* Issue update requests/success/failure\n* Poll requests/success/failure",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_create_action_total[3m])) * 60) or vector(0)",
       "legendFormat": "create requests"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_create_action_success_total[3m])) * 60) or vector(0)",
       "legendFormat": "create success"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_create_action_error_total[3m])) * 60) or vector(0)",
       "legendFormat": "create failures"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_update_action_total[3m])) * 60) or vector(0)",
       "legendFormat": "update requests"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_update_action_success_total[3m])) * 60) or vector(0)",
       "legendFormat": "update success"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_update_action_error_total[3m])) * 60) or vector(0)",
       "legendFormat": "update failures"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_poll_action_total[3m])) * 60) or vector(0)",
       "legendFormat": "poll requests"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_poll_action_success_total[3m])) * 60) or vector(0)",
       "legendFormat": "poll success"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_github_issue_poll_action_error_total[3m])) * 60) or vector(0)",
       "legendFormat": "poll failures"
      }
     ]
    },
    {
     "title": "Create successes",
     "type": "stat",
     "description": "Count that tracks the number of Github issues created successfully within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 51 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ticket_github_issue_create_action_success_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Create failures",
     "type": "stat",
     "description": "Count that tracks the number of Github issues that could not be created due to errors within the time range.\n\nPlease review that the Github credentials and instance details are valid. For more information on configuring the Github integration see: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/latest?topic=integrations-github",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 51 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ticket_github_issue_create_action_error_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update successes",
     "type": "stat",
     "description": "Count that tracks the number of Github issues updated successfully within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ticket_github_issue_update_action_success_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update failures",
     "type": "stat",
     "description": "Count that tracks the number of Github issues that could not be updated due to errors within the time range.\n\nIt is expected for a few update failures to occur when an incident is initially created. Incident creation is usually immediately followed by a few updates. The Github integration cannot process these updates until after the Github issue has been created, thus the updates will fail. Subsequent updates should succeed as normal.\n\nFor failures that occur after initial incident creation, please review that the Github credentials and instance details are valid. For more information on configuring the Github integration see: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/latest?topic=integrations-github",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ticket_github_issue_update_action_error_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jira issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rates",
     "type": "timeseries",
     "description": "Time series that tracks the request rates per minute for:\n* Issue creation requests/success/failure\n* Issue update requests/success/failure\n* Poll requests/success/failure",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_create_action_total[3m])) * 60) or vector(0)",
       "legendFormat": "create requests"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_create_action_success_total[3m])) * 60) or vector(0)",
       "legendFormat": "create success"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_create_action_error_total[3m])) * 60) or vector(0)",
       "legendFormat": "create failures"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_update_action_total[3m])) * 60) or vector(0)",
       "legendFormat": "update requests"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_update_action_success_total[3m])) * 60) or vector(0)",
       "legendFormat": "update success"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_update_action_error_total[3m])) * 60) or vector(0)",
       "legendFormat": "update failures"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_poll_action_total[3m])) * 60) or vector(0)",
       "legendFormat": "poll requests"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_poll_action_success_total[3m])) * 60) or vector(0)",
       "legendFormat": "poll success"
      },
      {
       "expr": "sum((rate(ibm_aiops_ticket_jira_issue_poll_action_error_total[3m])) * 60) or vector(0)",
       "legendFormat": "poll failures"
      }
     ]
    },
    {
     "title": "Create successes",
     "type": "stat",
     "description": "Count that tracks the number of Jira issues created successfully within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 60 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ticket_jira_issue_create_action_success_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Create failures",
     "type": "stat",
     "description": "Count that tracks the number of Jira issues that could not be created due to errors within the time range.\n\nPlease review that the Jira credentials and instance details are valid. For more information on configuring the Jira integration see: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/latest?topic=integrations-jira",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 60 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ticket_jira_issue_create_action_error_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update successes",
     "type": "stat",
     "description": "Count that tracks the number of Jira issues updated successfully within the time range.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 64 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ticket_jira_issue_update_action_success_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update failures",
     "type": "stat",
     "description": "Count that tracks the number of Jira issues that could not be updated due to errors within the time range.\n\nIt is expected for a few update failures to occur when an incident is initially created. Incident creation is usually immediately followed by a few updates. The Jira integration cannot process these updates until after the Jira ticket has been created, thus the updates will fail. Subsequent updates should succeed as normal.\n\nFor failures that occur after initial incident creation, please review that the Jira credentials and instance details are valid. For more information on configuring the Jira integration see: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/latest?topic=integrations-jira",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 64 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_ticket_jira_issue_update_action_error_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ChatOps notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rates",
     "type": "timeseries",
     "description": "Time series that tracks the ChatOps request rates per minute for:\n* Notification requests received (by internal ChatOps component)\n* notifications sent successfully\n* notification failures",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum((rate(ibm_aiops_chatops_slack_incidents_create_requests[3m]) * 60) or vector(0)) + sum((rate(ibm_aiops_chatops_teams_incidents_create_requests[3m]) * 60) or vector(0))",
       "legendFormat": "notification requests"
      },
      {
       "expr": "sum((rate(ibm_aiops_chatops_slack_incidents_create_success[3m]) * 60) or vector(0)) + sum((rate(ibm_aiops_chatops_teams_incidents_create_success[3m]) * 60) or vector(0))",
       "legendFormat": "notifications sent"
      },
      {
       "expr": "sum((rate(ibm_aiops_chatops_slack_incidents_created_errors[3m]) * 60) or vector(0)) + sum((rate(ibm_aiops_chatops_teams_incidents_created_errors[3m]) * 60) or vector(0))",
       "legendFormat": "notification failures"
      }
     ]
    },
    {
     "title": "Notifications sent",
     "type": "stat",
     "description": "Count that tracks the number of notifications successfully sent to the external Chat Platform (Slack/Teams) within the time range.",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 106 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_create_success[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_create_success[$__range]) or vector(0))",
       "legendFormat": "notifications requests sent"
      }
     ]
    },
    {
     "title": "Notification failures",
     "type": "stat",
     "description": "Count that tracks the number of notifications that could not be sent to the external Chat Platform (Slack/Teams) due to errors within the time range.\n\nPlease review that the ChatOps credentials and channel ids are valid. For more information on configuring the ChatOps integrations, see:\n* MS Teams: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/latest?topic=integrations-microsoft-teams-integration\n* Slack: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/latest?topic=integrations-slack-integration",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 106 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_created_errors[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_created_errors[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Notification times",
     "type": "bargauge",
     "description": "Histogram displaying the ChatOps notification times. This shows the time elapsed from incident creation to ChatOps notification. \n\nThis gives insight into the speed at which users are being notified of incidents via ChatOps.\n\nValues on the bottom are ranges of time in seconds. Values on the top are the number of notifications that were sent in that time range.\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 109 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_notifications_5[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_notifications_5[$__range]) or vector(0))",
       "legendFormat": "< 5s"
      },
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_notifications_10[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_notifications_10[$__range]) or vector(0))",
       "legendFormat": "5-10s"
      },
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_notifications_15[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_notifications_15[$__range]) or vector(0))",
       "legendFormat": "10-15s"
      },
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_notifications_30[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_notifications_30[$__range]) or vector(0))",
       "legendFormat": "15-30s"
      },
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_notifications_60[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_notifications_60[$__range]) or vector(0))",
       "legendFormat": "30-60s"
      },
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_notifications_300[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_notifications_300[$__range]) or vector(0))",
       "legendFormat": "1-5m"
      },
      {
       "expr": "sum(increase(ibm_aiops_chatops_slack_incidents_notifications_Inf[$__range]) or vector(0)) + sum(increase(ibm_aiops_chatops_teams_incidents_notifications_Inf[$__range]) or vector(0))",
       "legendFormat": "> 5m"
      }
     ]
    }
   ]
  }
 ]
}