INSERT INTO INCIDENTS_REPORTER_STATUS (
    tenantid,
    id,
    createdTime,
    createdBy,
    title,
    description,
    langId,
    priority,
    state,
    lastChangedTime,
    owner,
    team,
    alerts,
    similarIncidents,
    splitIncidents,
    probableCauseAlerts,
    tickets,
    chatOpsIntegrations,
    resourceId,
    policyId
) VALUES (
    'cfd95b7e-3bc7-4006-a4a8-a73a79c71255',
    '24fba2e3-0000-4000-8000-000000000002',
    $1,
    'Sue',
    'service card payment is down 1',
    'card payment is down expection null pointer 1',
    'eng',
    1,
    'unassigned',
    $2,
    '-',
    '-',
    50,
    3,
    4,
    5,
    6,
    7,
    'someresourceid',
    'somepolicyid'
);
