# Default values for clusterbackup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "icr.io/cpopen/cp4waiops/cp4aiops-bcdr@sha256:b4e1ac6cd3e665d82b6a8735af2555483266e10fa1b27118f817870b03acd711"
  pullPolicy: Always
schedule: ""
backupStorageLocation: ""
rwxStorageClass: ""
backupNameSuffix: ""
aiopsNamespace: ""
csNamespace: ""
oadpNamespace: ""
redisBackupPod: ""
redisPVC: ""
redisSecret: ""
esBackupPVC: "aiops-opensearch-snapshot-repo"
ttl: 72h0m0s
enabledNamespaces:
  - '"ibm-common-services"'
  - '"cp4aiops"'
enabledComponents:
  - '"AIOPS"'
  - '"IA"'
