apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: bcdr-np
 namespace: {{ .Values.aiopsNamespace }}
spec:
 podSelector:
  matchLabels:
   cluster.opensearch.cloudpackopen.ibm.com: aiops-opensearch
 ingress:
 - from:
   - namespaceSelector:
      matchLabels:
       kubernetes.io/metadata.name: {{ .Values.oadpNamespace }}
 policyTypes:
 - Ingress
