- hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  vars_files:
    - vars.yml
  vars:
    ibm_entitlement_key: ""
  roles:
    - aiops
    - get_entitlement_key
    - ibm.mas_devops.db2
    - cognosanalytics

