apiVersion: v1
kind: Pod
metadata:
  name: backup-postgres
  labels:
    restic-backup-pod: t
    component: backup-postgres
spec:
  containers:
  - name: backup
    image: redhat/ubi8:8.6-754
    command: ["sleep"]
    args: ["infinity"]
    volumeMounts:
            - name: backup
              mountPath: /usr/share/backup
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
  volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: postgres-backup-data
  restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: STORAGE_CLASS
