---
- name: Get pod name for encryption command target
  command: "/usr/local/bin/kubectl get pods -l app.kubernetes.io/name=topology -n {{ AIOPS_NAMESPACE }} -o=jsonpath='{.items[0].metadata.name}'"
  register: pod_name
  failed_when: pod_name.rc != 0

- name: Encrypt observer password
  command: "kubectl -n {{ AIOPS_NAMESPACE }} exec -ti {{ pod_name.stdout }} -- java -jar /opt/ibm/topology-service/topology-service.jar encrypt_password --password '{{ secret_token }}'"
  register: observer_password
  failed_when: observer_password.rc != 0

- set_fact: observer_pw="{{ observer_password.stdout }}"
