---
- name: Get secret name
  shell: "/usr/local/bin/kubectl get secret -n {{ RS_NAMESPACE }} --no-headers | grep {{ AIOPS_NAMESPACE }}-{{ CUSTOMER }}-k8s-account-token | head -1 | awk '{print $1}'"
  register: output

- name: Set ops pod
  set_fact: aiops_secret="{{ output.stdout }}"
  
- name: Pull token from secret
  shell: "/usr/local/bin/kubectl get secret -n {{ RS_NAMESPACE }} {{ aiops_secret }} -o=jsonpath='{.data.token}' | base64 -d"
  register: token

- name: Set secret_token 
  set_fact: secret_token="{{ token.stdout }}"
#  set_fact: secret_token="KficTns38F9zkcr1x6h2ol22chWcBwq7/qCfZoyGEWo="  # hard coded dummy token

- name: "Saving copy of secret token to {{ WORKDIR }}/{{ ROBOTSHOP_SECRET_TOKEN }}"
  local_action: copy content="{{ secret_token }}" dest="{{ WORKDIR }}/{{ ROBOTSHOP_SECRET_TOKEN }}"
