---
- name: Get secret data
  command: "oc get secret -l release=evtmanager-topology -n {{ AIOPS_NAMESPACE }} -o yaml"
  register: evt_secret

- set_fact: secret_data="{{ evt_secret.stdout }}"

- name: Create file with secret data
  local_action: copy content="{{ secret_data }}" dest="{{ WORKDIR }}/evt_secret.yaml"

- name: Add certificate to yaml
  lineinfile:
    dest: "{{ WORKDIR }}/evt_secret.yaml"
    line: "    {{ KUBE_CERT_NAME }}: {{ kube_certificate }}"
    insertafter: '^\s*crypto.key:.*'
    state: present

- name: Apply yaml file
  command: "kubectl apply -f {{ WORKDIR }}/evt_secret.yaml -n {{ AIOPS_NAMESPACE }}"

