{
 "title": "IBM Cloud Pak for AIOps - Prometheus Monitoring Stack",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Prometheus Overiew\n\nThe Prometheus monitoring stack can be monitored with its own components.\nThis dashboard tracks the health and stability of the Prometheus server pods which scrape and store metrics, as well as the PVCs\nwhere they store metrics.\n\n#### OCP:\n- **prometheus-k8s** pods scrape metrics from all OpenShift resources including: nodes, pods, containers, PVC, etc.\n- **prometheus-user-workload** pods scrape custom metrics from AIOps component pods\n\nTo learn more about configuring your Prometheus monitoring stack on OCP see: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/4.12.0?topic=grafana-configuring-enabling-openshift-container-platform-monitoring\n\n#### Linux:\n- **prometheus-prometheus** pod scrapes metrics from Kubernetes resources including: nodes, pods, containers, PVC, as well as custom metrics from AIOps component pods."
     }
    },
    {
     "type": "stat",
     "description": "Count that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the component pod uptime time series to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Server Pods",
     "type": "table",
     "description": "Current pod phase of the prometheus server pods.\n\nOCP: If monitoring is enabled and configured, there should be a total of 4 pods running: 2 prometheus-k8s pods & 2 prometheus-user-workload pods\n\nLinux: If monitoring is enabled and configured, there should be a single prometheus server pod running: prometheus-prometheus",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Server Pods Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"POD\", container!=\"config-reloader\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"config-reloader\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"POD\", container!=\"config-reloader\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"POD\", container!=\"config-reloader\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"POD\", container!=\"config-reloader\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"POD\", container!=\"config-reloader\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"POD\", container!=\"config-reloader\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*prometheus-k8s.*|.*prometheus-user.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"POD\", container!=\"config-reloader\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus CPU Usage",
     "type": "timeseries",
     "description": "Prometheus CPU Usage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*prometheus-k8s.*|.*prometheus-prometheus.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*prometheus-k8s.*|.*prometheus-prometheus.*\", container!=\"config-reloader\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*prometheus-k8s.*|.*prometheus-prometheus.*\", container!=\"config-reloader\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Prometheus Memory Usage",
     "type": "timeseries",
     "description": "Prometheus Memory Usage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"prometheus-k8s.*|.*prometheus-prometheus.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"prometheus-k8s.*|.*prometheus-prometheus.*\", container!=\"config-reloader\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"prometheus-k8s.*|.*prometheus-prometheus.*\", container!=\"config-reloader\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Prometheus user workload CPU Usage (OCP only)",
     "type": "timeseries",
     "description": "Prometheus user workload CPU Usage. OCP only, no metrics will appear for linux-based installations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*prometheus-user-workload.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*prometheus-user-workload.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*prometheus-user-workload.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Prometheus User Workload Memory Usage (OCP only)",
     "type": "timeseries",
     "description": "Prometheus User Workload Memory Usage. OCP only, no metrics will appear for linux-based installations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*prometheus-user-workload.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*prometheus-user-workload.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*prometheus-user-workload.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bound monitoring PVCs",
     "type": "gauge",
     "description": "Count of monitoring PVCs in a \"bound\" state",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_status_phase{namespace=~\"openshift-monitoring|openshift-user-workload-monitoring|prometheus-operator\",phase=\"Bound\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PVC Usage",
     "type": "gauge",
     "description": "PVC usage percentage for each PVC in the monitoring namespaces, thresholds of 85% & 95% usage.\n\nPrometheus PVC usage should stabilize after reaching its retention period. If it appears that the PVC is filling up too fast, expand PVC or shorten the retention period to ensure the PVC doesn't run out.",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sort_desc(kubelet_volume_stats_used_bytes{namespace=~\"openshift-monitoring|openshift-user-workload-monitoring\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"openshift-monitoring|openshift-user-workload-monitoring\"} * 100) or sort_desc(kubelet_volume_stats_used_bytes{exported_namespace=~\"prometheus-operator\"}/kubelet_volume_stats_capacity_bytes{exported_namespace=~\"prometheus-operator\"} * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unbound PVC",
     "type": "gauge",
     "description": "Count of \"lost\" or \"pending\" PVCs in the monitoring namespaces.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (phase)(kube_persistentvolumeclaim_status_phase{namespace=~\"openshift-monitoring|openshift-user-workload-monitoring|prometheus-operator\",phase!~\"Bound\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PVC Usage (max & current)",
     "type": "timeseries",
     "description": "Max and current PVC usage. Prometheus PVC usage should stabilize after reaching its retention period. If it appears that the PVC is filling up too fast, expand PVC or shorten the retention period to ensure the PVC doesn't run out.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"openshift-monitoring|openshift-user-workload-monitoring\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"openshift-monitoring|openshift-user-workload-monitoring\"} * 100) or sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{exported_namespace=~\"prometheus-operator\"}/kubelet_volume_stats_capacity_bytes{exported_namespace=~\"prometheus-operator\"} * 100)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  }
 ]
}