apiVersion: v1
kind: Pod
metadata:
  name: backup-metastore
  labels:
    restic-backup-pod: t
    component: backup-metastore
spec:
  containers:
  - name: backup
    image: redhat/ubi9:latest
    command: ["sleep"]
    args: ["infinity"]
    volumeMounts:
            - name: data
              mountPath: /usr/share/backup
    imagePullPolicy: IfNotPresent
  volumes:
        - name: data
          persistentVolumeClaim:
            claimName: metastore-backup-data
  restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metastore-backup-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: STORAGE_CLASS
