# Default values for clusterbackup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "icr.io/cpopen/cp4waiops/cp4waiops-bcdr@sha256:4992024da03ce81f939199ffdf7059d9179e712947d39c226d4aafda4bd15a4e"
  pullPolicy: Always
schedule: ""
backupStorageLocation: ""
backupNameSuffix: ""
aiopsNamespace: ""
csNamespace: ""
oadpNamespace: ""
redisBackupPod: ""
redisPVC: ""
redisSecret: ""
esBackupPVC: ""
ttl: 72h0m0s
enabledNamespaces:
  - '"ibm-common-services"'
  - '"cp4aiops"'
enabledComponents:
  - '"AIOPS"'
  - '"IA"'
