{
 "title": "IBM Cloud Pak for AIOps Component - Metric Integrations",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Metric Integrations Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Metric Integrations Overview\n\nIBM Cloud Pak for AIOps is capable of ingesting metrics from a variety of sources.\nThis dashboard will provide insight into the health & performance of the following integrations: AWS CloudWatch, AppDynamics, Instana, New Relic, Splunk, Zabbix\n\nOnly integrations that have been created in the IBM Cloud Pak for AIOps Integrations page will have metrics visible here."
     }
    },
    {
     "title": "Lowest Pod Uptimes",
     "type": "stat",
     "description": "The 5 lowest uptimes within the component pods. Pod restarts can impact functionality, review the pod table and uptime graph for more details.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() -topk(5, sum(kube_pod_start_time{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric Integration Component Pods",
     "type": "table",
     "description": "This panel displays the number of active pods for all defined Metric integration pods. Pods stuck in \"Pending\" or \"Unknown\" states for prolonged periods of time are problematic and may result in loss of functionality.",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric Integration Component Pods Uptime",
     "type": "timeseries",
     "description": "Pod uptimes for metric integrations.",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utlization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 265 },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 265 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 266 },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 266 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*nrelic-conn.*|.*instana-conn.*|.*appd-conn.*|.*awscw-conn.*|.*splunk-conn.*|.*zabbix-conn.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AWS CloudWatch Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 267 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*awscw-conn.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*awscw-conn.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*awscw-conn.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "AWS CloudWatch Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 267 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*awscw-conn.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*awscw-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*awscw-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "AppDynamics Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 274 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*appd-conn.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*appd-conn.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*appd-conn.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "AppDynamics Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*appd-conn.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*appd-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*appd-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Instana Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 281 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*instana-conn.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*instana-conn.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*instana-conn.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Instana Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*instana-conn.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*instana-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*instana-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "New Relic Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 288 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*nrelic-conn.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*nrelic-conn.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*nrelic-conn.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "New Relic Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*nrelic-conn.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*nrelic-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*nrelic-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Splunk Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 295 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*splunk-conn.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*splunk-conn.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*splunk-conn.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Splunk Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*splunk-conn.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*splunk-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*splunk-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    },
    {
     "title": "Zabbix Integration CPU Usage ",
     "type": "timeseries",
     "description": "This panel displays the CPU usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 302 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*zabbix-conn.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*zabbix-conn.*\", resource=\"cpu\"})",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*zabbix-conn.*\", resource=\"cpu\"}) ",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Zabbix Integration Memory Usage ",
     "type": "timeseries",
     "description": "This panel displays the memory usage over time of the integration pod(s). Spikes can occur during data collection, monitor these to ensure the integration is not ingesting more than it can process. Create more integrations as needed to ensure stable collection and timely processing.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*zabbix-conn.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*zabbix-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "requests "
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*zabbix-conn.*\", resource=\"memory\"}) ",
       "legendFormat": "limits "
      }
     ]
    }
   ]
  },
  {
   "title": "Total Metrics Collected",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric messages collected ",
     "type": "stat",
     "description": "Total number of metric messages collected within the time range across all metric integrations. Metric messages are made up of 1-x actual metrics pertaining to a particular resource. Check the \"Total Metrics Collected\" for the total number of actual metrics.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 698 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_instana_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric messages collected per integration ",
     "type": "piechart",
     "description": "Total number of metric messages collected by each integration within the time range. Metric messages are made up of 1-x actual metrics pertaining to a particular resource.",
     "gridPos": { "h": 10, "w": 19, "x": 5, "y": 698 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_instana_metrics_data_size_objects_sum[$__range])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Metrics Collected",
     "type": "stat",
     "description": "Total number of metric messages collected within the time range across all metric integrations. This contains the total number of individual metrics contained within all the metric messages.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 730 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric message collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of metric messages collected by each integration. Metric messages are made up of 1-x actual metrics pertaining to a particular resource.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 735 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(rate(ibm_aiops_metricconnector_instana_metrics_data_size_objects_sum[3m])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AppDynamics Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1701 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_run_count_total[$__range]) or vector(0)) + sum(increase(ibm_aiops_metricconnector_appdynamics_live_metrics_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1701 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_appdynamics_live_metrics_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1701 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_appdynamics_live_metrics_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric messages collected per integration ",
     "type": "piechart",
     "description": "Total number of metric messages collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1701 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric message collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of metric messages collected by each integration.",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1701 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric messages collected ",
     "type": "stat",
     "description": "Total number of metric messages collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1794 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_appdynamics_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_appdynamics_live_metrics_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AWS CloudWatch Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1702 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_run_count_total[$__range]) or vector(0)) + sum(increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1702 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1702 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric messages collected per integration ",
     "type": "piechart",
     "description": "Total number of metric messages collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1702 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric message collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of metric messages collected by each integration.",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1702 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric messages collected ",
     "type": "stat",
     "description": "Total number of metric messages collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1705 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_cloudwatch_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_cloudwatch_live_metrics_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Instana Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 437 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_instana_metrics_run_count_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 437 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_instana_metrics_error_count_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 437 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_instana_interuptted_count_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric messages collected per integration ",
     "type": "piechart",
     "description": "Total number of metric messages collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_instana_metrics_data_size_objects_sum[$__range])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric message collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of metric messages collected by each integration.",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_metricconnector_instana_metrics_data_size_objects_sum[3m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric messages collected ",
     "type": "stat",
     "description": "Total number of metric messages collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 440 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_instana_metrics_data_size_objects_sum[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "New Relic Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 447 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_newrelic_historical_metrics_run_count_total[$__range]) or vector(0)) + sum(increase(ibm_aiops_metricconnector_newrelic_live_metrics_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 447 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_newrelic_historical_metrics_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_newrelic_live_metrics_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 447 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_newrelic_historical_metrics_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_newrelic_live_metrics_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric messages collected per integration ",
     "type": "piechart",
     "description": "Total number of metric messages collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric message collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of metric messages collected by each integration.",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric messages collected ",
     "type": "stat",
     "description": "Total number of metric messages collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 450 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_newrelic_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_newrelic_live_metrics_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Splunk Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 457 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_splunk_historical_metrics_run_count_total[$__range]) or vector(0)) + sum(increase(ibm_aiops_metricconnector_splunk_live_metrics_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 457 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_splunk_historical_metrics_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_splunk_live_metrics_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 457 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_splunk_historical_metrics_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_splunk_live_metrics_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric messages collected per integration ",
     "type": "piechart",
     "description": "Total number of metric messages collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 457 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase (ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric message collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of metric messages collected by each integration.",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 457 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric messages collected ",
     "type": "stat",
     "description": "Total number of metric messages collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 460 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_splunk_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_splunk_live_metrics_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zabbix Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric collections",
     "type": "stat",
     "description": "Number of collections conducted within the time range.",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 467 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_zabbix_historical_metrics_run_count_total[$__range]) or vector(0)) + sum(increase(ibm_aiops_metricconnector_zabbix_live_metrics_run_count_total[$__range]))or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "Number of collections that resulted in an error within the time range. Errors will end the current collection, but will not impact future collections from happening. The subsequent collection after an error will proceed as scheduled.",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 467 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_zabbix_historical_metrics_error_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_zabbix_live_metrics_error_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Interruptions",
     "type": "stat",
     "description": "Number of collections that were interrupted within the time range. Interruptions are more severe than errors and will prevent any further collections. Review the component pods for error logs.",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 467 },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_zabbix_historical_metrics_interrupted_count_total[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_zabbix_live_metrics_interrupted_count_total[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric messages collected per integration ",
     "type": "piechart",
     "description": "Total number of metric messages collected within the time range per integration.",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 467 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    increase(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[$__range])\n  )\n  + on(pod) group_left() (\n    increase(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[$__range]) or 0 * increase(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[$__range])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric message collection rate ",
     "type": "timeseries",
     "description": "Per-second rates of metric messages collected by each integration.",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 467 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  (\n    rate(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[3m])\n  )\n  + on(pod) group_left() (\n    rate(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[3m]) or 0 * rate(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[3m])\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Metric messages collected ",
     "type": "stat",
     "description": "Total number of metric messages collected within the time range.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 470 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_metricconnector_zabbix_historical_metrics_data_size_objects_sum[$__range]) or vector(0)) +\nsum(increase(ibm_aiops_metricconnector_zabbix_live_metrics_data_size_objects_sum[$__range]) or vector(0))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}