kind: Pod
apiVersion: v1
metadata:
  name: dummy-db
  labels:
    app: dummy-db
spec:
  containers:
    - image: redhat/ubi9:latest
      command: ["sleep"]
      args: ["infinity"]
      name: ubuntu
      volumeMounts:
        - name: mongodump
          mountPath: "/dump"
  volumes:
    - name: mongodump
      persistentVolumeClaim:
        claimName: my-mongodump
