{
 "title": "IBM Cloud Pak for AIOps - Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage (5m avg)",
     "type": "gauge",
     "description": "Percentage of CPU usage across all nodes taken at 5 minute averages",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^.*$\"}[5m])) / sum (machine_cpu_cores{ node=~\"^.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "gauge",
     "description": "Percentage of memory usage across all nodes",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^.*$\"}) / sum (machine_memory_bytes{node=~\"^.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "gauge",
     "description": "Percentage of filesystem usage across all nodes",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^.*$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Sum of the 5 min avg of the cumulative cpu time consumed in seconds for all nodes",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^.*$\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "description": "Total number of logical cores across all nodes",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{node=~\"^.*$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^.*$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{node=~\"^.*$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^.*$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^.*$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Nodes",
     "type": "timeseries",
     "description": "Sum of nodes in a \"ready\" state across a period of time",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_info{node=~\".*\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\", node=~\".*\", status!=\"true\"})",
       "legendFormat": "Unavailable"
      }
     ]
    },
    {
     "title": "Disk Pressure",
     "type": "stat",
     "description": "Number of nodes experiencing low disk space (default value of 85%)",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\".*\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "Memory Pressure",
     "type": "stat",
     "description": "Number of nodes experiencing memory pressure",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", node=~\".*\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "PID Pressure",
     "type": "stat",
     "description": "Number of nodes experiencing PID pressure",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", node=~\".*\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "Unschedulable",
     "type": "stat",
     "description": "Number of nodes that are unschedulable. New pods cannot be scheduled on nodes in this state.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{node=~\".*\"})"
      }
     ]
    },
    {
     "title": "Out of Disk",
     "type": "stat",
     "description": "Number of nodes that are out of disk storage",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\".*\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Network Unavailable",
     "type": "stat",
     "description": "Number of nodes with a \"NetworkUnavailable\" status",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", node=~\".*\", status!=\"false\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bound PVC",
     "type": "gauge",
     "description": "Count of PVCs in a \"bound\" state",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase=\"Bound\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unbound PVC",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (phase)(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase!~\"Bound\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PVC Usage",
     "type": "gauge",
     "description": "PVC usage percentage for each PVC in the namespace, thresholds of 85% & 95% usage",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}/kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"} * 100) or sort_desc(kubelet_volume_stats_used_bytes{exported_namespace=\"$namespace\"}/kubelet_volume_stats_capacity_bytes{exported_namespace=\"$namespace\"} * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PVC Usage (max & current)",
     "type": "timeseries",
     "description": "Max and current PVC usage",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}/kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"} * 100) or sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{exported_namespace=\"$namespace\"}/kubelet_volume_stats_capacity_bytes{exported_namespace=\"$namespace\"} * 100)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Running",
     "type": "stat",
     "description": "Number of pods in a \"running\" state in $namespace namespace",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "stat",
     "description": "Number of pods in a \"succeeded\" state in $namespace namespace",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "stat",
     "description": "Number of pods in a \"failed\" state in $namespace namespace",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "stat",
     "description": "Number of pods in an \"unknown\" state in $namespace namespace",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    },
    {
     "title": "Pods pending",
     "type": "table",
     "description": "Number of pods in a \"pending\" state in $namespace namespace",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting_reason{namespace=\"$namespace\"}) by (pod, reason)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}