{
 "title": "IBM Cloud Pak for AIOps Component - Topology",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Topology Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Topology Overiew\n\nThe IBM Cloud Pak for AIOps Topology system is comprised of the following components:\n- ***Observers***: Responsible for obtaining near real-time data from resources and feeding it into the AIOps system via Kafka.\n- ***Status Service***: Correlates new alerts to their topological resources.\n- ***Merge Service***: Handles the merging of resources into composite resources.\nIt also handles merge rules and group template processing.\n- ***Topology Service***: Main topology component that manages the JanusGraph database.\nIt processes topological objects (vertices) & their relationships (edges) with a number of processes.\n- ***Layout Service***: Provides graph layout algorithms for displaying topological data in the UI.\n- ***Inventory Service***: Search engine for optimzing topological queries.\n\n**Dependencies:**\n- ***JanusGraph***: Highly scalable graph database used for composition and storage of vertices and edges. Uses Cassandra for actual storage.\n- ***Cassandra***: Topological database. Topological objects (vertices) and their relationships (edges) are stored here.\n- ***Kafka***: Message Broker system for ingesting requests and outputting results.\n- ***Postgres***: Search engine database used for optimzing queries.\n"
     }
    },
    {
     "title": "Lowest Pod Uptimes",
     "type": "stat",
     "description": "The 5 lowest uptimes within the component pods. Pod restarts can impact functionality, review the pod table and uptime graph for more details.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() -topk(5, sum(kube_pod_start_time{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topology Component Pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topology Component Pods Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 6183 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 6183 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 7832 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 7832 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topology Service CPU Usage",
     "type": "timeseries",
     "description": "Topology Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7925 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-topology-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-topology-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-topology-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Topology Service Memory Usage",
     "type": "timeseries",
     "description": "Topology Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7925 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-topology.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-topology-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-topology-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Status Service CPU Usage",
     "type": "timeseries",
     "description": "Status Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7931 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-status-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-status-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-status-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Status Service Memory Usage",
     "type": "timeseries",
     "description": "Status Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7931 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-status-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-status-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-status-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Merge Service CPU Usage",
     "type": "timeseries",
     "description": "Merge Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7937 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-merge-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-merge-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-merge-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Merge Service Memory Usage",
     "type": "timeseries",
     "description": "Merge Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7937 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-merge.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-merge-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-merge-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Layout Service CPU Usage",
     "type": "timeseries",
     "description": "Layout Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7943 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-layout-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-layout-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-layout-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Layout Service Memory Usage",
     "type": "timeseries",
     "description": "Layout Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7943 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-layout.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-layout-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-layout-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Inventory Service CPU Usage",
     "type": "timeseries",
     "description": "Inventory Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7949 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-inventory-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-inventory-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-inventory-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Inventory Service Memory Usage",
     "type": "timeseries",
     "description": "Inventory Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7949 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-inventory.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-inventory-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-inventory-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1789 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*topology-postgres.*|aiops-topology-cassandra.*|iaf-system-kafka.*\", pod!~\".*job.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Policy Automation dependency pods",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1790 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\",  phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Policy Automation Dependencies Uptime",
     "type": "timeseries",
     "description": "Pod Uptimes for Policy Automation dependency pods",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1790 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 1797 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1797 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 1798 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1798 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\"aiops-topology-cassandra.*|.*topology-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cassandra CPU Usage ",
     "type": "timeseries",
     "description": "Cassandra: The policies store, managed by the Policy Registry Service.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1799 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-cassandra.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-cassandra.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Cassandra Memory Usage",
     "type": "timeseries",
     "description": "Cassandra: The policies store, managed by the Policy Registry Service.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1799 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-cassandra.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-cassandra.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Kafka CPU Usage ",
     "type": "timeseries",
     "description": "Message Broker system used within Policy Automation Component.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1803 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"iaf-system-kafka.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"iaf-system-kafka.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"iaf-system-kafka.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Kafka Memory Usage",
     "type": "timeseries",
     "description": "Message Broker system used within Policy Automation Component.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1803 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"iaf-system-kafka.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"iaf-system-kafka.*\", resource=\"memory\"}) by (pod)",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"iaf-system-kafka.*\", resource=\"memory\"}) by (pod)",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Postgres CPU Usage ",
     "type": "timeseries",
     "description": "Replacement DB for Policy Registry Store.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1807 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*topology-postgres.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*topology-postgres.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*topology-postgres.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Postgres Memory  Usage",
     "type": "timeseries",
     "description": "Replacement DB for Policy Registry Store.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1807 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*topology-postgres.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*topology-postgres.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*topology-postgres.*\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology Observer(s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Observer Traffic (messages)",
     "type": "stat",
     "description": "Total count of messages sent by Topology Observers to the central Topology Service within the time range.",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_ingress_task_seconds_count{service=\"aiops-topology-topology\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Observer Traffic (bytes)",
     "type": "stat",
     "description": "Total number of bytes sent by Topology Observers to the central Topology Service within the time range.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_kafka_incoming_size_bytes_sum{service=\"aiops-topology-topology\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topology Observer message processing times (seconds)",
     "type": "bargauge",
     "description": "Histogram displaying the message processing times of incoming traffic from Topology Observers via Kafka occurring within the time range. \n\nThis gives insight into the volume of messages being fed into Topology by the Observers and how quickly those messages are being processed.\n\nValues on the left are ranges of time in seconds, values on the right are the number of requests that fall into that time range.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_ingress_task_seconds_bucket{service=\"aiops-topology-topology\"}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Traffic per Observer",
     "type": "bargauge",
     "description": "Count of messages sent by each Topology Observer to the central Topology Service within the time range.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_ingress_task_seconds_count{service=\"aiops-topology-topology\"}[$__range])) by (observer)",
       "legendFormat": "{{observer}}"
      }
     ]
    },
    {
     "title": "Traffic rates per Observer",
     "type": "timeseries",
     "description": "TODO: ADD CONTEXT",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_ingress_task_seconds_count{service=\"aiops-topology-topology\"}[3m])) by (observer)",
       "legendFormat": "{{observer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Message I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming traffic (bytes)",
     "type": "stat",
     "description": "Number of incoming bytes for the topology sub-component.",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_kafka_incoming_size_bytes_sum{service!=\"aiops-topology-observer-service\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming traffic (messages/seconds)",
     "type": "timeseries",
     "description": "Rate of incoming messages for the topology sub-components. Messages represent requests received by the sub-component and are broken down further into ",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_kafka_incoming_size_bytes_count{service!=\"aiops-topology-observer-service\"}[3m])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming traffic (bytes/seconds)",
     "type": "timeseries",
     "description": "Rate of incoming bytes for the topology sub-components.",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_kafka_incoming_size_bytes_sum{service!=\"aiops-topology-observer-service\"}[3m])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outgoing traffic (bytes)",
     "type": "stat",
     "description": "Number of outgoing bytes for the topology sub-component.",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_kafka_outgoing_size_bytes_sum{service!=\"aiops-topology-observer-service\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outgoing traffic (messages/second)",
     "type": "timeseries",
     "description": "Rate of outgoing messages for the topology sub-components.",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_kafka_outgoing_size_bytes_count{service!=\"aiops-topology-observer-service\"}[3m])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outgoing traffic (bytes/second)",
     "type": "timeseries",
     "description": "Rate of outgoing bytes for the topology sub-components.",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_kafka_outgoing_size_bytes_sum{service!=\"aiops-topology-observer-service\"}[3m])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processing times (Topology service)",
     "type": "bargauge",
     "description": "Histogram displaying the message processing times processed by the topology sub-component within the time range. \n\nThis gives insight into the volume of messages being fed into the topology sub-component and how quickly those messages are being processed.\n\nValues on the left are ranges of time in seconds, values on the right are the number of requests that fall into that time range.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_ingress_task_seconds_bucket{service=\"aiops-topology-topology\"}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing times (Status service)",
     "type": "bargauge",
     "description": "Histogram displaying the message processing times processed by the topology sub-component within the time range. \n\nThis gives insight into the volume of messages being fed into the topology sub-component and how quickly those messages are being processed.\n\nValues on the left are ranges of time in seconds, values on the right are the number of requests that fall into that time range.",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_kafka_time_seconds_bucket{service=\"aiops-topology-status\"}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing times (Merge service)",
     "type": "bargauge",
     "description": "Histogram displaying the message processing times processed by the topology sub-component within the time range. \n\nThis gives insight into the volume of messages being fed into the topology sub-component and how quickly those messages are being processed.\n\nValues on the left are ranges of time in seconds, values on the right are the number of requests that fall into that time range.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_kafka_time_seconds_bucket{service=\"aiops-topology-merge\"}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing times (Inventory service)",
     "type": "bargauge",
     "description": "Histogram displaying the message processing times processed by the topology sub-component within the time range. \n\nThis gives insight into the volume of messages being fed into the topology sub-component and how quickly those messages are being processed.\n\nValues on the left are ranges of time in seconds, values on the right are the number of requests that fall into that time range.",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_kafka_time_seconds_bucket{service=\"aiops-topology-inventory\"}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Message Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Processing Lag",
     "type": "timeseries",
     "description": "This time series displays the message processing lag over time per topology sub-component. Message lag is the number of messages that are waiting to be processed. The higher the lag, the longer it will take for new messages to get processed.\n\nLag will increase during message bursts but should always stabilize and ideally decrease. If lag is steadily increasing over time, more resources may need to be allocated to sub-component to ensure timely message processing.",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 547 },
     "fieldConfig": { "defaults": { "unit": "msgs" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_kafka_lag{service!=\"aiops-topology-observer-service\"}) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Processing Lag (current)",
     "type": "gauge",
     "description": "Current message lag per component. Message lag is the number of messages that are waiting to be processed. The higher the lag, the longer it will take for new messages to get processed.\n\nLag will increase during message bursts but should always stabilize and ideally decrease. If lag is steadily increasing over time, more resources may need to be allocated to sub-component to ensure timely message processing.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 547 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_kafka_lag{service!=\"aiops-topology-observer-service\"}) by (service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Message Processing Lag (Topology Service)",
     "type": "timeseries",
     "description": "This time series displays the message processing lag over time for the Topology Service. This is the central component that acts as the point of entry for messages coming in from Topological observers. As such, spikes are expected to occur at each collection interval.\n\nThe legend on the right shows: \"<topic> - <partition>\". Topics act as roads between components, allowing messages to pass from one to the other. Topics are made up of partitions, like lanes in the road.  Messages relating to a particular resource, are typically sent to the same partition to maintain ordering. Too much traffic on one partition is what causes lag.\n\nLag will increase during message bursts but should always stabilize and ideally decrease. If lag is steadily increasing over time, more resources may need to be allocated to sub-component to ensure timely message processing.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 554 },
     "fieldConfig": { "defaults": { "unit": "msgs" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_kafka_lag{service=\"aiops-topology-topology\"}) by (topic, partition)",
       "legendFormat": "{{topic}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Message Processing Lag (Inventory Service)",
     "type": "timeseries",
     "description": "This time series displays the message processing lag over time for the Inventory Service.\n\nThe legend on the right shows: \"<topic> - <partition>\". Topics act as roads between components, allowing messages to pass from one to the other. Topics are made up of partitions, like lanes in the road.  Messages relating to a particular resource, are typically sent to the same partition to maintain ordering. Too much traffic on one partition is what causes lag.\n\nLag will increase during message bursts but should always stabilize and ideally decrease. If lag is steadily increasing over time, more resources may need to be allocated to sub-component to ensure timely message processing.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 554 },
     "fieldConfig": { "defaults": { "unit": "msgs" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_kafka_lag{service=\"aiops-topology-inventory\"}) by (topic, partition)",
       "legendFormat": "{{topic}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Message Processing Lag (Status Service)",
     "type": "timeseries",
     "description": "This time series displays the message processing lag over time for the Status Service.\n\nThe legend on the right shows: \"<topic> - <partition>\". Topics act as roads between components, allowing messages to pass from one to the other. Topics are made up of partitions, like lanes in the road.  Messages relating to a particular resource, are typically sent to the same partition to maintain ordering. Too much traffic on one partition is what causes lag.\n\nLag will increase during message bursts but should always stabilize and ideally decrease. If lag is steadily increasing over time, more resources may need to be allocated to sub-component to ensure timely message processing.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 560 },
     "fieldConfig": { "defaults": { "unit": "msgs" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_kafka_lag{service=\"aiops-topology-status\"}) by (topic, partition)",
       "legendFormat": "{{topic}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Message Processing Lag (Merge Service)",
     "type": "timeseries",
     "description": "This time series displays the message processing lag over time for the Merge Service.\n\nThe legend on the right shows: \"<topic> - <partition>\". Topics act as roads between components, allowing messages to pass from one to the other. Topics are made up of partitions, like lanes in the road.  Messages relating to a particular resource, are typically sent to the same partition to maintain ordering. Too much traffic on one partition is what causes lag.\n\nLag will increase during message bursts but should always stabilize and ideally decrease. If lag is steadily increasing over time, more resources may need to be allocated to sub-component to ensure timely message processing.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 560 },
     "fieldConfig": { "defaults": { "unit": "msgs" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_kafka_lag{service=\"aiops-topology-merge\"}) by (topic, partition)",
       "legendFormat": "{{topic}} - {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database queries",
     "type": "stat",
     "description": "Count of database queries executed by the Topology Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 421 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-topology\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database query rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 421 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-topology\"}[3m])) by (pod)",
       "legendFormat": "requests - {{pod}}"
      }
     ]
    },
    {
     "title": "Database request time quantiles",
     "type": "timeseries",
     "description": "Timeline of Topology database request times, made by the Topology Service, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 421 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_janusgraph_query_graph_seconds{service=\"aiops-topology-topology\"}) by (quantile, pod)",
       "legendFormat": "{{quantile}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Database query failures",
     "type": "stat",
     "description": "Count of database query failures made by the Topology Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 495 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-topology\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Layout Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database queries",
     "type": "stat",
     "description": "Count of database queries executed by the Layout Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 422 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-layout\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database query rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 422 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-layout\"}[3m])) by (pod)",
       "legendFormat": "requests - {{pod}}"
      }
     ]
    },
    {
     "title": "Database request time quantiles",
     "type": "timeseries",
     "description": "Timeline of Topology database request times, made by the Layout Service, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 422 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_janusgraph_query_graph_seconds{service=\"aiops-topology-layout\"}) by (quantile, pod)",
       "legendFormat": "{{quantile}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Database query failures",
     "type": "stat",
     "description": "Count of database query failures made by the Layout Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 488 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-layout\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Status Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database queries",
     "type": "stat",
     "description": "Count of database queries executed by the Status Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 423 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-status\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database query rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 423 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-status\"}[3m])) by (pod)",
       "legendFormat": "requests - {{pod}}"
      }
     ]
    },
    {
     "title": "Database request time quantiles",
     "type": "timeseries",
     "description": "Timeline of Topology database request times, made by the Status Service, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 423 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_janusgraph_query_graph_seconds{service=\"aiops-topology-status\"}) by (quantile, pod)",
       "legendFormat": "{{quantile}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Database query failures",
     "type": "stat",
     "description": "Count of database query failures made by the Status Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 427 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-status\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Merge Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database queries",
     "type": "stat",
     "description": "Count of database queries executed by the Merge Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 432 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-merge\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database query rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 432 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-merge\"}[3m])) by (pod)",
       "legendFormat": "requests - {{pod}}"
      }
     ]
    },
    {
     "title": "Database request time quantiles",
     "type": "timeseries",
     "description": "Timeline of Topology database request times, made by the Merge Service, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 432 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_janusgraph_query_graph_seconds{service=\"aiops-topology-merge\"}) by (quantile, pod)",
       "legendFormat": "{{quantile}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Database query failures",
     "type": "stat",
     "description": "Count of database query failures made by the Merge Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 436 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-merge\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Inventory Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query API response time quantiles",
     "type": "timeseries",
     "description": "Timeline of  Topology Inventory Service ***query api endpoint*** response times, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 441 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_inventory_service_api_query_seconds{service=\"aiops-topology-inventory\"}) by (quantile, operation, pod)",
       "legendFormat": "{{quantile}} - {{operation}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Suggest API response time quantiles",
     "type": "timeseries",
     "description": "Timeline of  Topology Inventory Service ***suggest api endpoint*** response times, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 441 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_inventory_service_api_suggest_seconds{service=\"aiops-topology-inventory\"}) by (quantile, operation, pod)",
       "legendFormat": "{{quantile}} - {{operation}} - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}