apiVersion: v1
data:
  restore-data.json: |-
    {
      "backupName": "{{ .Values.backupName }}"
    }
  aiops-config.json: |-
    {
      "aiopsNamespace": "{{ .Values.aiopsNamespace }}",
      "csNamespace": "{{ .Values.csNamespace }}",
      "oadpNamespace": "{{ .Values.oadpNamespace }}",
      "aiopsVersion": "4.8.1"
    }
kind: ConfigMap
metadata:
  name: restore-config
  namespace: {{ .Values.oadpNamespace }}
