apiVersion: batch/v1
kind: Job
metadata:
  name: aiops-restore-job
  namespace: velero
spec:
  backoffLimit: 0
  template:
    spec:
      imagePullSecrets:
        - name: restore-secret
      serviceAccountName: restore-sa
      volumes:
        - name: restore-data-config
          configMap:
            name: restore-config
        - name: aiops-config
          configMap:
            name: restore-config
        - name: workdir
          emptyDir: {}
      containers:
      - image: "icr.io/cpopen/cp4waiops/cp4waiops-bcdr@sha256:7262f64be3f1d0c9bf425866f454f4c8f0e424b7a2af86c5328995886a4a55ed"
        imagePullPolicy: Always
        name: aiops-restore
        command: ["/bin/bash", "/bcdr/restore/restore.sh","-aiops"]
        resources: {}
        env:
        - name: WORKDIR
          value: "/bcdr"
        volumeMounts:
          - name: restore-data-config
            mountPath: /bcdr/restore/restore-data.json
            subPath: restore-data.json 
          - name: aiops-config
            mountPath: /bcdr/common/aiops-config.json
            subPath: aiops-config.json
          - mountPath: /workdir
            name: workdir
      restartPolicy: Never
