{
 "title": "IBM Cloud Pak for AIOps Component - Topology",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Topology Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Topology Overiew\n\nThe IBM Cloud Pak for AIOps Topology system is comprised of the following components:\n- ***Observers***: Responsible for obtaining near real-time data from resources and feeding it into the AIOps system via Kafka.\n- ***Status Service***: Correlates new alerts to their topological resources.\n- ***Merge Service***: Handles the merging of resources into composite resources.\nIt also handles merge rules and group template processing.\n- ***Topology Service***: Main topology component that manages the JanusGraph database.\nIt processes topological objects (vertices) & their relationships (edges) with a number of processes.\n- ***Layout Service***: Provides graph layout algorithms for displaying topological data in the UI.\n- ***Inventory Service***: Search engine for optimzing topological queries.\n\n**Dependencies:**\n- ***JanusGraph***: Highly scalable graph database used for composition and storage of vertices and edges. Uses Cassandra for actual storage.\n- ***Cassandra***: Topological database. Topological objects (vertices) and their relationships (edges) are stored here.\n- ***Kafka***: Message Broker system for ingesting requests and outputting results.\n- ***Postgres***: Search engine database used for optimzing queries.\n"
     }
    },
    {
     "type": "stat",
     "description": "Count that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the component pod uptime time series to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 416 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topology Component Pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 417 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topology Component Pods Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 417 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", pod!~\".*schema.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\".*-topology-.*\", pod!~\".*cassandra.*\", pod!~\".*file-observer.*\", pod!~\".*kubernetes-observer.*\", pod!~\".*observer.*\",pod!~\".*api.*\", pod!~\".*aiopsedge.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topology Service CPU Usage",
     "type": "timeseries",
     "description": "Topology Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-topology-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-topology-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-topology-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Topology Service Memory Usage",
     "type": "timeseries",
     "description": "Topology Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-topology.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-topology-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-topology-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Status Service CPU Usage",
     "type": "timeseries",
     "description": "Status Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-status-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-status-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-status-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Status Service Memory Usage",
     "type": "timeseries",
     "description": "Status Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-status-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-status-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-status-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Merge Service CPU Usage",
     "type": "timeseries",
     "description": "Merge Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-merge-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-merge-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-merge-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Merge Service Memory Usage",
     "type": "timeseries",
     "description": "Merge Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-merge.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-merge-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-merge-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Layout Service CPU Usage",
     "type": "timeseries",
     "description": "Layout Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-layout-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-layout-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-layout-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Layout Service Memory Usage",
     "type": "timeseries",
     "description": "Layout Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-layout.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-layout-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-layout-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Inventory Service CPU Usage",
     "type": "timeseries",
     "description": "Inventory Service CPU Usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-inventory-.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-inventory-.*\", pod!~\".*job.*\", pod!~\".*schema.*\"  , resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-inventory-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Inventory Service Memory Usage",
     "type": "timeseries",
     "description": "Inventory Service Memory Usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-inventory.*\", pod!~\".*schema.*\" ,pod!~\".*job.*\", container!=\"\", container!=\"POD\"}) by(pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-inventory-.*\", pod!~\".*job.*\", pod!~\".*schema.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-inventory-.*\",pod!~\".*job.*\" , pod!~\".*schema.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology Dependencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Count that tracks the number of pods that were newly created within the time range.\n\nNew pods indicate restarts may have occurred which could result in loss of functionality. Review the pod uptime graph to see if any gaps in uptime occurred.\n\nNew pods don't always indicate a problem and in some cases are part of routine processing and scaling. ",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(((sum((time() - kube_pod_start_time{pod=~\".*edb-postgres.*|aiops-topology-cassandra.*|iaf-system-kafka.*\", pod!~\".*job.*\"}) - $__range_s) by (pod)) < 60) <= bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Policy Automation dependency pods",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\",  phase=~\"Running|Pending|Unknown\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Policy Automation Dependencies Uptime",
     "type": "timeseries",
     "description": "Pod Uptimes for Policy Automation dependency pods",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() -sum(kube_pod_start_time{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 156 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) * 0.8 <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded 80% of their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 156 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) * 0.8 <= max(max_over_time(container_memory_working_set_bytes{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of pods that have exceeded their CPU limits within the time range. This will result in CPU throttling and potentially temporary loss of functionality.\n\nThis will only compare against the ***current*** CPU limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 157 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", resource=\"cpu\"}) by (pod)) <= max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of component pods that have exceeded their memory limits within the time range.\n\nThis will only compare against the ***current*** memory limit of each pod. If the limits were updated within the time range, the count may be inaccurate.",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 157 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((((max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\", resource=\"memory\"}) by (pod)) <= max(max_over_time(container_memory_working_set_bytes{pod=~\"aiops-topology-cassandra.*|.*edb-postgres.*|iaf-system-kafka.*\", pod!~\".*job.*\", container!=\"\", container!=\"POD\"}[$__range])) by (pod)) or vector(0)) > bool 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cassandra CPU Usage ",
     "type": "timeseries",
     "description": "Cassandra: The policies store, managed by the Policy Registry Service.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"aiops-topology-cassandra.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-cassandra.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Cassandra Memory Usage",
     "type": "timeseries",
     "description": "Cassandra: The policies store, managed by the Policy Registry Service.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"aiops-topology-cassandra.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"aiops-topology-cassandra.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"aiops-topology-cassandra.*\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Kafka CPU Usage ",
     "type": "timeseries",
     "description": "Message Broker system used within Policy Automation Component.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"iaf-system-kafka.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"iaf-system-kafka.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"iaf-system-kafka.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Kafka Memory Usage",
     "type": "timeseries",
     "description": "Message Broker system used within Policy Automation Component.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\"iaf-system-kafka.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\"iaf-system-kafka.*\", resource=\"memory\"}) by (pod)",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\"iaf-system-kafka.*\", resource=\"memory\"}) by (pod)",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Postgres CPU Usage ",
     "type": "timeseries",
     "description": "Replacement DB for Policy Registry Store.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*edb-postgres.*\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*edb-postgres.*\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*edb-postgres.*\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Postgres Memory  Usage",
     "type": "timeseries",
     "description": "Replacement DB for Policy Registry Store.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{pod=~\".*edb-postgres.*\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "usage - {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{pod=~\".*edb-postgres.*\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{pod=~\".*edb-postgres.*\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology Observer(s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Observer Traffic",
     "type": "stat",
     "description": "Total count of messages sent by Topology Observers to the central Topology Service within the time range.",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_ingress_task_seconds_bucket{service=\"aiops-topology-topology\", le=\"+Inf\"}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Topology Observer message processing times (seconds)",
     "type": "bargauge",
     "description": "Histogram displaying the message processing times of incoming traffic from Topology Observers via Kafka occurring within the time range. \n\nThis gives insight into the volume of messages being fed into Topology by the Observers and how quickly those messages are being processed.\n\nValues on the left are ranges of time in seconds, values on the right are the number of requests that fall into that time range.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_ingress_task_seconds_bucket{service=\"aiops-topology-topology\"}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Traffic per Observer",
     "type": "bargauge",
     "description": "Count of messages sent by each Topology Observer to the central Topology Service within the time range.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_ingress_task_seconds_bucket{service=\"aiops-topology-topology\", le=\"+Inf\"}[$__range])) by (observer)",
       "legendFormat": "{{observer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database queries",
     "type": "stat",
     "description": "Count of database queries executed by the Topology Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 891 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-topology\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database query rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 891 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-topology\"}[3m])) by (pod)",
       "legendFormat": "requests - {{pod}}"
      }
     ]
    },
    {
     "title": "Database request time quantiles",
     "type": "timeseries",
     "description": "Timeline of Topology database request times, made by the Topology Service, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 891 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_janusgraph_query_graph_seconds{service=\"aiops-topology-topology\"}) by (quantile, pod)",
       "legendFormat": "{{quantile}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Database query failures",
     "type": "stat",
     "description": "Count of database query failures made by the Topology Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 959 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-topology\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Layout Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database queries",
     "type": "stat",
     "description": "Count of database queries executed by the Layout Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 892 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-layout\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database query rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 892 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-layout\"}[3m])) by (pod)",
       "legendFormat": "requests - {{pod}}"
      }
     ]
    },
    {
     "title": "Database request time quantiles",
     "type": "timeseries",
     "description": "Timeline of Topology database request times, made by the Layout Service, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 892 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_janusgraph_query_graph_seconds{service=\"aiops-topology-layout\"}) by (quantile, pod)",
       "legendFormat": "{{quantile}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Database query failures",
     "type": "stat",
     "description": "Count of database query failures made by the Layout Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 936 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-layout\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Status Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database queries",
     "type": "stat",
     "description": "Count of database queries executed by the Status Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 893 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-status\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database query rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 893 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-status\"}[3m])) by (pod)",
       "legendFormat": "requests - {{pod}}"
      }
     ]
    },
    {
     "title": "Database request time quantiles",
     "type": "timeseries",
     "description": "Timeline of Topology database request times, made by the Status Service, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 893 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_janusgraph_query_graph_seconds{service=\"aiops-topology-status\"}) by (quantile, pod)",
       "legendFormat": "{{quantile}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Database query failures",
     "type": "stat",
     "description": "Count of database query failures made by the Status Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 937 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-status\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Merge Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database queries",
     "type": "stat",
     "description": "Count of database queries executed by the Merge Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 894 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-merge\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database query rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 894 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(ibm_aiops_topo_janusgraph_query_graph_total{service=\"aiops-topology-merge\"}[3m])) by (pod)",
       "legendFormat": "requests - {{pod}}"
      }
     ]
    },
    {
     "title": "Database request time quantiles",
     "type": "timeseries",
     "description": "Timeline of Topology database request times, made by the Merge Service, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 894 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_janusgraph_query_graph_seconds{service=\"aiops-topology-merge\"}) by (quantile, pod)",
       "legendFormat": "{{quantile}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Database query failures",
     "type": "stat",
     "description": "Count of database query failures made by the Merge Service within the time range",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 938 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ibm_aiops_topo_janusgraph_query_graph_exceptions{service=\"aiops-topology-merge\"}[$__range])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Inventory Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query API response time quantiles",
     "type": "timeseries",
     "description": "Timeline of  Topology Inventory Service ***query api endpoint*** response times, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 895 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_inventory_service_api_query_seconds{service=\"aiops-topology-inventory\"}) by (quantile, operation, pod)",
       "legendFormat": "{{quantile}} - {{operation}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Suggest API response time quantiles",
     "type": "timeseries",
     "description": "Timeline of  Topology Inventory Service ***suggest api endpoint*** response times, represented in quantiles.\n\nA quantile represents a percentage of the requests. Quantiles are computed across 10 minute sliding windows.\n\n***p50=1s*** means 50% of all requests in the window took less than or equal to 1s\n\n***p98=3s*** means 98% of all requests in the window took less than or equal to 3s\n\n***p99.9=5s*** means 99.9% of all requests in the window took less than or equal to 5s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 895 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(ibm_aiops_topo_inventory_service_api_suggest_seconds{service=\"aiops-topology-inventory\"}) by (quantile, operation, pod)",
       "legendFormat": "{{quantile}} - {{operation}} - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}