{
 "title": "IBM Cloud Pak for AIOps - Usage",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Objective",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
     "options": {
      "content": "# Objective\nThe goal of this dashboard is to provide visibility\n on the level of traffic flowing through the \n environment and make sure that Cloud Pak for\n  AIOps is properly configured to handle it\n  as described in the [sizing documentation](https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/4.6.1?topic=planning-hardware-requirements#aimgr_custom). "
     }
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event ingestion rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of events ingested into the system over 3m averages. \n\nKafka topic: cp4waiops-cartridge.lifecycle.input.events ",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.lifecycle.input.events\"}[3m]))",
       "legendFormat": "New events"
      }
     ]
    },
    {
     "title": "Events ingested in time range",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.lifecycle.input.events\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alert request rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of alert create/update requests over 3m averages. \n\nKafka topic: cp4waiops-cartridge.irdatalayer.changes.alerts",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.alerts\"}[3m]))",
       "legendFormat": "Alert creates & updates"
      }
     ]
    },
    {
     "title": "Alerts created/updated in time range",
     "type": "stat",
     "description": "Count that tracks alert create/update requests in time range. Updates can come from events, manual user changes, and Cloud Pak for AIOps enrichments.",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.alerts\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Incidents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incident request rates",
     "type": "timeseries",
     "description": "Shows the per-second rate of incident create/update requests over 3m averages. \n\nKafka topic: cp4waiops-cartridge.irdatalayer.changes.stories",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.stories\"}[3m]))",
       "legendFormat": "Incident creates/updates"
      }
     ]
    },
    {
     "title": "Incidents created/updated in time range",
     "type": "stat",
     "description": "Count that tracks incident create/update requests in time range. Updates can come from alerts, manual user changes, and IBM Cloud Pak for AIOps enrichments.",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.irdatalayer.changes.stories\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of logs ingested into the system over 1m averages. Log integrations can be created in the Cloud Pak for AIOps integrations page.\n\nKafka topic: cp4waiops-cartridge-logs-.*-raw",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge-logs-.*-raw\"}[1m]))",
       "legendFormat": "Incoming logs"
      }
     ]
    },
    {
     "title": "Logs ingested in time range",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge-logs-.*-raw\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric messages rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of metric messages ingested into the system over 3m averages. Metric messages contain x amount of actual metrics. Metric integrations can be created in the IBM Cloud Pak for AIOps integrations page.\n\nKafka topic: cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.raw",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.raw\"}[3m]))",
       "legendFormat": "Incoming messages"
      }
     ]
    },
    {
     "title": "Metric messages ingested in time range",
     "type": "stat",
     "description": "Count of metric messages ingested within the time range. Metric messages may contain 1-x amount of actual metrics. Metric integrations can be created in the IBM Cloud Pak for AIOps integrations page.\n\nTo view an accurate count, select a time window that is equal to, or longer than the metric aggregation interval . For example, if the aggregation interval is 5 minutes, select a time window from the time picker that is at least 5 minutes long. The aggregation interval is viewable and configurable in the IBM Cloud Pak for AIOps integrations page.\n\nKafka topic: cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.raw\n",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.raw\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metrics rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of metrics ingested into the system over 3m averages. Metric integrations can be created in the IBM Cloud Pak for AIOps integrations page.\n\nKafka topic: cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "metrics/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated\"}[3m]))",
       "legendFormat": "Incoming metrics"
      }
     ]
    },
    {
     "title": "Metrics ingested in time range",
     "type": "stat",
     "description": "Count of metrics ingested within the time range. Metric integrations can be created in the IBM Cloud Pak for AIOps integrations page.\n\nTo view an accurate count, select a time window that is equal to, or longer than the metric aggregation interval . For example, if the aggregation interval is 5 minutes, select a time window from the time picker that is at least 5 minutes long. The aggregation interval is viewable and configurable in the IBM Cloud Pak for AIOps integrations page.\n\nKafka topic: cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.aggregated\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Runbooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runbook execution rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of runbooks executed in the system over 1m averages. Runbooks can be created and configured under the Cloud Pak for AIOps Automations page.\n\nKafka topic: cp4waiops-cartridge.lifecycle.output.rba-exec-requests",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "executions/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.lifecycle.output.rba-exec-requests\"}[3m]))",
       "legendFormat": "Runbook executions"
      }
     ]
    },
    {
     "title": "Runbooks executed in time range",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.lifecycle.output.rba-exec-requests\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ServiceNow Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound ServiceNow traffic rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of requests flowing from ServiceNow to Cloud Pak for AIOps* over 3m averages. This includes: historic incident/change request records, alert updates, incident updates, and new change requests. ServiceNow integrations can be created in the Cloud Pak for AIOps integrations page.\n\n\\* All API calls originate from Cloud Pak for AIOps, but 2-way traffic is simulated via polling.\n\nKafka topic: cp4waiops-cartridge.incident",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.incident\"}[3m]))",
       "legendFormat": "Inbound ServiceNow traffic"
      }
     ]
    },
    {
     "title": "Inbound ServiceNow traffic",
     "type": "stat",
     "description": "Count that tracks the number of requests flowing from ServiceNow to Cloud Pak for AIOps* in time range. This includes: historic incident/change request records, alert updates, incident updates, and new change requests. ServiceNow integrations can be created in the Cloud Pak for AIOps integrations page.\n\n\\* All API calls originate from Cloud Pak for AIOps, but 2-way traffic is simulated via polling.",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.incident\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbound ServiceNow traffic rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of requests flowing from Cloud Pak for AIOps to ServiceNow over 3m averages. This includes: incident create/update, alert update, & change risk assessment requests\n\nKafka topic: cp4waiops-cartridge.snow-handlers",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.snow-handlers\"}[3m]))",
       "legendFormat": "Outbound ServiceNow traffic"
      }
     ]
    },
    {
     "title": "Outbound ServiceNow traffic",
     "type": "stat",
     "description": "Count that tracks the number of requests flowing from Cloud Pak for AIOps to ServiceNow in time range. This includes: incident create/update, alert update, & change risk assessment messages",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.snow-handlers\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Tickets (Jira and Github only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ticket creation rate",
     "type": "timeseries",
     "description": "Shows the per-second rate of Jira/Github issues created by Cloud Pak for AIOps. over 1m averages.\n\nKafka topic: cp4waiops-cartridge.itsmincidentresponse\n\nWARNING: This metric will not be accurate if a ServiceNow integration is also in use. This issue will be corrected in a future release of the product. (ServiceNow metrics are not affected.)",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "tickets/s" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"cp4waiops-cartridge.itsmincidentresponse\"}[3m]))",
       "legendFormat": "Ticket creation"
      }
     ]
    },
    {
     "title": "Tickets created in time range",
     "type": "stat",
     "description": "Count that tracks the number of Jira/Github issues created by Cloud Pak for AIOps in time range.\n\nWARNING: This metric will not be accurate if a ServiceNow integration is also in use. This issue will be corrected in a future release of the product. (ServiceNow metrics are not affected.)",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4waiops-cartridge.itsmincidentresponse\"}[$__range]) or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}