# Default values for clusterbackup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "icr.io/cpopen/cp4waiops/cp4aiops-bcdr@sha256:9fb440d169117ece54e7acc8a9d2a20d10c444e49ea23016e3c519ce1be32d24"
  pullPolicy: Always
schedule: ""
backupStorageLocation: ""
rwxStorageClass: ""
backupNameSuffix: ""
aiopsNamespace: ""
csNamespace: ""
oadpNamespace: ""
redisBackupPod: ""
redisPVC: ""
redisSecret: ""
esBackupPVC: "aiops-opensearch-snapshot-repo"
ttl: 72h0m0s
enabledNamespaces:
  - '"ibm-common-services"'
  - '"cp4aiops"'
enabledComponents:
  - '"AIOPS"'
  - '"IA"'
